// ================================================================
// WORLD DISEASE MONITOR — data.js — Base OMS/CDC/ECDC
// ================================================================
const DB = {
diseases:[
{id:'dengue',name:'Dengue',emoji:'🦟',risk:'critical',color:'#ef4444',cases:4280000,deaths:21400,mort:0.5,countries:87,r0:9.2,trend:18,cat:'Arbovirose',pathogen:'Flavivirus DENV 1-4',vector:'Aedes aegypti/albopictus',transmission:'Piqûre moustique',host:'Moustiques Aedes, primates',incub:'4–10 jours',regions:['Asie SE','Amériques','Afrique','Océanie'],lat:-14,lng:-50,desc:'Résurgence massive 2024-2026. São Paulo état urgence. 4 sérotypes. Dengue hémorragique forme grave.',vaccine:{name:'Qdenga / Dengvaxia',maker:'Takeda / Sanofi',eff:80,status:'Disponible',approved:'UE, Brésil, Indonésie, Thaïlande',note:'Qdenga: 2 doses SC, dès 4 ans.',link:'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue'},econ:{direct:47,tour:12,agri:3,health:890,gdp:-0.8,jobs:420000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue',t:'WHO'},{n:'CDC',u:'https://www.cdc.gov/dengue/',t:'CDC'}]},
{id:'mpox',name:'Mpox Clade Ib',emoji:'🔴',risk:'critical',color:'#f97316',cases:92400,deaths:1848,mort:2.0,countries:36,r0:6.1,trend:22,cat:'Orthopoxvirus',pathogen:'MPXV clade Ib',vector:'Contact direct',transmission:'Contact peau, fluides, sexuel',host:'Rongeurs, primates',incub:'5–21 jours',regions:['Afrique centrale','Europe','Asie SE'],lat:0,lng:25,desc:'Urgence OMS août 2024. Clade Ib plus transmissible. 3 cas Thaïlande juin 2026.',vaccine:{name:'Jynneos / ACAM2000',maker:'Bavarian Nordic',eff:85,status:'Disponible',approved:'FDA/EMA 2022',note:'2 doses SC à 28j.',link:'https://www.who.int/news-room/fact-sheets/detail/mpox'},econ:{direct:8,tour:4,agri:0,health:340,gdp:-0.12,jobs:85000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/mpox',t:'WHO'},{n:'Africa CDC',u:'https://africacdc.org/disease/mpox/',t:'Africa CDC'}]},
{id:'h5n1',name:'Grippe Aviaire H5N1',emoji:'🐦',risk:'critical',color:'#f59e0b',cases:68,deaths:21,mort:30.9,countries:12,r0:2.1,trend:45,cat:'Influenza A',pathogen:'Influenza A(H5N1) HPAI',vector:'Contact oiseaux/bovins',transmission:'Contact animaux infectés',host:'Oiseaux, bovins, mammifères',incub:'2–5 jours',regions:['USA','Asie','Europe','Afrique'],lat:39,lng:-98,desc:'Mutation PB2 627K souches bovines USA. Adaptation mammifère critique. Mortalité 30.9%.',vaccine:{name:'mRNA-1045 / stocks H5N1',maker:'Moderna / GSK',eff:null,status:'Essais',approved:'Stocks stratégiques Phase 2/3',note:'Déploiement 90j si pandémie.',link:'https://www.who.int/publications/m/item/avian-influenza-a(h5n1)-situation-updates'},econ:{direct:22,tour:180,agri:95,health:1200,gdp:-2.1,jobs:1200000},src:[{n:'OMS',u:'https://www.who.int/publications/m/item/avian-influenza-a(h5n1)-situation-updates',t:'WHO'},{n:'CDC',u:'https://www.cdc.gov/flu/avianflu/h5n1-people.htm',t:'CDC'}]},
{id:'cholera',name:'Choléra',emoji:'💧',risk:'critical',color:'#06b6d4',cases:780000,deaths:5460,mort:0.7,countries:24,r0:5.4,trend:8,cat:'Bactérie',pathogen:'Vibrio cholerae O1/O139',vector:'Eau/nourriture',transmission:'Fécale-orale',host:'Environnement aquatique',incub:'Qques heures–5j',regions:['Afrique','Asie','Haïti','Yémen','Syrie'],lat:10,lng:40,desc:'7ème pandémie. Foyers Éthiopie, Nigéria, RDC, Haïti, Soudan (48K cas/6sem.), Yémen.',vaccine:{name:'Shanchol / EUVICHOL-Plus',maker:'Eubiologics',eff:79,status:'Disponible',approved:'OMS préqualifiée — GAVI',note:'2 doses orales 14j.',link:'https://www.who.int/news-room/fact-sheets/detail/cholera'},econ:{direct:12,tour:8,agri:15,health:420,gdp:-0.4,jobs:320000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/cholera',t:'WHO'}]},
{id:'covid19',name:'COVID-19',emoji:'🦠',risk:'high',color:'#8b5cf6',cases:1240000,deaths:6200,mort:0.5,countries:184,r0:7.8,trend:-5,cat:'Coronavirus',pathogen:'SARS-CoV-2 (XEC/LP8.1)',vector:'Aérosols',transmission:'Aérosols, gouttelettes',host:'Chauves-souris → pangolins',incub:'2–14 jours',regions:['Mondial'],lat:30,lng:0,desc:'Sous-variants XEC et LP.8.1. Vagues saisonnières. Données LIVE dans onglet COVID.',vaccine:{name:'Comirnaty / Spikevax / Nuvaxovid',maker:'Pfizer / Moderna / Novavax',eff:62,status:'Disponible',approved:'Mondial',note:'Rappel annuel OMS.',link:'https://covid19.who.int/'},econ:{direct:340,tour:95,agri:12,health:2800,gdp:-0.5,jobs:2400000},src:[{n:'WHO Dashboard',u:'https://covid19.who.int/',t:'WHO'},{n:'disease.sh',u:'https://disease.sh',t:'API'}]},
{id:'measles',name:'Rougeole',emoji:'💢',risk:'high',color:'#ec4899',cases:320000,deaths:4800,mort:1.5,countries:41,r0:14,trend:22,cat:'Paramyxovirus',pathogen:'Measles morbillivirus',vector:'Aérosols (2h)',transmission:'Aérosols — ultra-contagieux',host:'Humain uniquement',incub:'7–14 jours',regions:['Afrique','Asie','Europe Est','Amériques'],lat:10,lng:20,desc:'R₀=14 — le plus contagieux. Résurgence 41 pays post-COVID. Roumanie 1200 cas.',vaccine:{name:'ROR / Priorix / MMR-II',maker:'GSK / Merck',eff:97,status:'Disponible',approved:'Mondial 1963',note:'2 doses 12-15 mois + rappel.',link:'https://www.who.int/news-room/fact-sheets/detail/measles'},econ:{direct:5,tour:2,agri:0,health:280,gdp:-0.09,jobs:120000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/measles',t:'WHO'},{n:'ECDC',u:'https://www.ecdc.europa.eu/en/measles',t:'ECDC'}]},
{id:'malaria',name:'Paludisme',emoji:'🦟',risk:'high',color:'#10b981',cases:5800000,deaths:87000,mort:1.5,countries:85,r0:4.2,trend:2,cat:'Parasite',pathogen:'Plasmodium falciparum/vivax',vector:'Anophèles femelle',transmission:'Piqûre Anophèles',host:'Moustiques Anophèles',incub:'7–14 jours',regions:['Afrique sub.','Asie Sud','Amériques'],lat:-5,lng:25,desc:'608K décès/an, majorité enfants <5 ans Afrique. Premier vaccin antiparasitaire R21.',vaccine:{name:'R21/Matrix-M / RTS,S',maker:'Serum Institute / GSK',eff:77,status:'Disponible',approved:'15 pays africains',note:'HISTORIQUE — 1er vaccin antiparasitaire.',link:'https://www.who.int/news-room/fact-sheets/detail/malaria'},econ:{direct:38,tour:22,agri:28,health:640,gdp:-1.3,jobs:580000},src:[{n:'WHO Malaria',u:'https://www.who.int/teams/global-malaria-programme/reports/world-malaria-report-2024',t:'WHO'}]},
{id:'tb',name:'Tuberculose XDR',emoji:'🫁',risk:'high',color:'#64748b',cases:1100000,deaths:176000,mort:16.0,countries:30,r0:1.8,trend:3,cat:'Bactérie',pathogen:'Mycobacterium tuberculosis XDR',vector:'Aérosols (toux)',transmission:'Aérosols espaces confinés',host:'Aucun',incub:'2–12 semaines',regions:['Asie Sud','Afrique','Europe Est'],lat:28,lng:80,desc:'1.3M décès/an. XDR résistante. VIH x20 risque.',vaccine:{name:'BCG / M72/AS01E',maker:'Multiples / GSK',eff:70,status:'Disponible',approved:'BCG mondial 1921',note:'BCG nourrissons. M72 Phase 3.',link:'https://www.who.int/news-room/fact-sheets/detail/tuberculosis'},econ:{direct:28,tour:5,agri:0,health:890,gdp:-0.6,jobs:420000},src:[{n:'WHO TB',u:'https://www.who.int/teams/global-tuberculosis-programme/tb-reports',t:'WHO'}]},
{id:'marburg',name:'Virus Marburg',emoji:'🩸',risk:'critical',color:'#dc2626',cases:14,deaths:11,mort:78.6,countries:2,r0:1.2,trend:999,cat:'Filovirus',pathogen:'Marburgvirus (MARV)',vector:'Contact fluides',transmission:'Contact fluides infectés',host:'Chauves-souris Rousettus',incub:'2–21 jours',regions:['Tanzanie — Kagera'],lat:-3,lng:32,desc:'🚨 FOYER ACTIF Tanzanie: 14 cas, 11 décès (78.6%). Barrière sanitaire. AUCUN vaccin.',vaccine:{name:'cAd3-Marburg (Phase 2)',maker:'NIH/Janssen',eff:null,status:'Essais',approved:'Phase 1-2 compassionnel',note:'AUCUN vaccin. Soins soutien.',link:'https://www.who.int/news-room/fact-sheets/detail/marburg-virus-disease'},econ:{direct:1,tour:8,agri:0,health:45,gdp:-0.5,jobs:28000},src:[{n:'OMS Alertes',u:'https://www.who.int/emergencies/disease-outbreak-news',t:'WHO'}]},
{id:'nipah',name:'Virus Nipah',emoji:'🦇',risk:'watch',color:'#7c3aed',cases:8,deaths:6,mort:75.0,countries:2,r0:0.5,trend:10,cat:'Paramyxovirus',pathogen:'NiV (Nipah Virus)',vector:'Chauves-souris / malade',transmission:'Contact chauves-souris, sève palme',host:'Chauves-souris Pteropus',incub:'4–14 jours',regions:['Kerala Inde','Bangladesh'],lat:10,lng:76,desc:'PRIORITÉ 1 OMS Blueprint. Mortalité 40-75%. Kerala surveillance juin 2026.',vaccine:{name:'mAbs m102.4 / ARNm CEPI',maker:'CSIRO / CEPI',eff:null,status:'Essais',approved:'Compassionnel',note:'AUCUN vaccin approuvé.',link:'https://www.who.int/news-room/fact-sheets/detail/nipah-virus'},econ:{direct:0.5,tour:3,agri:2,health:28,gdp:-0.2,jobs:15000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/nipah-virus',t:'WHO'}]},
{id:'hiv',name:'VIH/SIDA',emoji:'🎗️',risk:'high',color:'#e11d48',cases:38400000,deaths:630000,mort:1.6,countries:195,r0:2.5,trend:-3,cat:'Rétrovirus',pathogen:'VIH-1 / VIH-2',vector:'Sang, sexuel, périnatal',transmission:'Sexuel, seringues, mère-enfant',host:'SIV chimpanzés → humains',incub:'2–4 semaines',regions:['Mondial (Afrique 60%+)'],lat:-5,lng:20,desc:'38.4M infectés. Lenakapavir 2×/an: 100% efficacité PURPOSE 1 (n=5338).',vaccine:{name:'Lenakapavir PrEP PURPOSE 1',maker:'Gilead Sciences',eff:100,status:'Essais',approved:'PrEP orale mondiale',note:'100% efficacité femmes Afrique.',link:'https://www.who.int/news-room/fact-sheets/detail/hiv-aids'},econ:{direct:26,tour:8,agri:18,health:2400,gdp:-1.8,jobs:1800000},src:[{n:'UNAIDS',u:'https://www.unaids.org/en/resources/fact-sheet',t:'ONU'}]},
{id:'amr',name:'Résistance Antimicrobienne',emoji:'💊',risk:'critical',color:'#be185d',cases:5000000,deaths:1270000,mort:25.4,countries:195,r0:null,trend:12,cat:'Résistance',pathogen:'Bactéries ESKAPE',vector:'Nosocomiale/alimentaire',transmission:'Hôpitaux, alimentation',host:'Agriculture',incub:'Variable',regions:['Mondial'],lat:20,lng:80,desc:'1.27M morts/an. Projection 10M/an 2050. Urgence silencieuse mondiale.',vaccine:{name:'Aucun vaccin global',maker:'—',eff:null,status:'Aucun',approved:'Plan OMS One Health',note:'Cefiderocol pour résistants.',link:'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance'},econ:{direct:340,tour:0,agri:120,health:4800,gdp:-3.5,jobs:4200000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance',t:'WHO'}]},
{id:'candida',name:'Candida auris',emoji:'🍄',risk:'high',color:'#d97706',cases:18400,deaths:8280,mort:45.0,countries:58,r0:null,trend:90,cat:'Champignon',pathogen:'Candida auris (résistant)',vector:'Nosocomiale',transmission:'Surfaces hospitalières',host:'Environnement',incub:'Variable',regions:['USA','Inde','Espagne','Afrique du Sud'],lat:40,lng:-95,desc:'45-60% mortalité USI. 90% résistant fluconazole. PRIORITÉ 1 CDC/OMS.',vaccine:{name:'Aucun — Échinocandines',maker:'Pfizer / Astellas',eff:null,status:'Aucun',approved:'Caspofongine (traitement)',note:'Olorofim pour résistants.',link:'https://www.cdc.gov/candida-auris/'},econ:{direct:4,tour:0,agri:0,health:280,gdp:-0.1,jobs:12000},src:[{n:'CDC',u:'https://www.cdc.gov/candida-auris/',t:'CDC'}]},
{id:'influenza',name:'Grippe H3N2/H1N1',emoji:'🤧',risk:'medium',color:'#0891b2',cases:3400000,deaths:291400,mort:8.6,countries:195,r0:1.4,trend:10,cat:'Influenza A',pathogen:'Influenza A H3N2/H1N1 + B',vector:'Gouttelettes/aérosols',transmission:'Gouttelettes, aérosols',host:'Oiseaux, porcs',incub:'1–4 jours',regions:['Mondial'],lat:45,lng:0,desc:'1 milliard cas/an. H3N2 dominant 2025-26. DONNÉES LIVE onglet Grippe.',vaccine:{name:'Vaxigrip Tetra / Fluzone HD',maker:'Sanofi / GSK / Seqirus',eff:50,status:'Disponible',approved:'Mondial — bi-annuel',note:'Rappel annuel. Fluzone HD +65 ans.',link:'https://www.who.int/tools/flunet'},econ:{direct:28,tour:12,agri:3,health:1200,gdp:-0.4,jobs:420000},src:[{n:'FluNet OMS',u:'https://www.who.int/tools/flunet',t:'WHO'}]},
{id:'hantavirus',name:'Hantavirus',emoji:'🐭',risk:'watch',color:'#4c1d95',cases:4200,deaths:840,mort:20.0,countries:34,r0:0,trend:5,cat:'Bunyavirus',pathogen:'Hantavirus SPHS/FHSR',vector:'Inhalation excréments',transmission:'Inhalation rongeurs',host:'Rongeurs Peromyscus',incub:'1–8 semaines',regions:['Amériques','Europe','Asie'],lat:-35,lng:-70,desc:'SPHS mortalité 35-40%. 3 cas Nouveau-Mexique juin 2026.',vaccine:{name:'Hantavax (Corée — FHSR)',maker:'Korea Green Cross',eff:70,status:'Disponible',approved:'Corée du Sud',note:'AUCUN vaccin SPHS.',link:'https://www.who.int/news-room/fact-sheets/detail/hantavirus-and-hantavirus-disease'},econ:{direct:1,tour:2,agri:3,health:68,gdp:-0.1,jobs:12000},src:[{n:'CDC',u:'https://www.cdc.gov/hantavirus/',t:'CDC'}]},
{id:'ebola',name:'Ebola',emoji:'🩸',risk:'watch',color:'#991b1b',cases:42,deaths:28,mort:66.7,countries:2,r0:1.5,trend:5,cat:'Filovirus',pathogen:'Ebolavirus ZEBOV',vector:'Contact fluides',transmission:'Contact fluides infectés',host:'Chauves-souris, gorilles',incub:'2–21 jours',regions:['RD Congo'],lat:-2,lng:28,desc:'RDC endémique. Vaccin Ervebo 97%. 400K doses stockées.',vaccine:{name:'Ervebo / Zabdeno+Mvabea',maker:'Merck / Janssen',eff:97,status:'Disponible',approved:'FDA 2019, EMA 2020',note:'Dose unique 97%.',link:'https://www.who.int/news-room/fact-sheets/detail/ebola-virus-disease'},econ:{direct:3,tour:12,agri:4,health:180,gdp:-2.0,jobs:95000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/ebola-virus-disease',t:'WHO'}]},
{id:'pertussis',name:'Coqueluche',emoji:'😮‍💨',risk:'high',color:'#0f766e',cases:245000,deaths:89425,mort:36.5,countries:190,r0:12,trend:25,cat:'Bactérie',pathogen:'Bordetella pertussis',vector:'Gouttelettes',transmission:'Gouttelettes ultra-contagieux',host:'Humain uniquement',incub:'7–20 jours',regions:['Mondial — résurgence'],lat:15,lng:100,desc:'R₀=12-17. Philippines +370%, Chine record. Mortelle nourrissons <3 mois.',vaccine:{name:'DTPa / Tdap Boostrix',maker:'GSK / Sanofi',eff:85,status:'Disponible',approved:'Mondial',note:'Rappel Tdap grossesse 28-32 SA.',link:'https://www.who.int/news-room/fact-sheets/detail/pertussis'},econ:{direct:2,tour:1,agri:0,health:185,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/pertussis',t:'WHO'}]},
{id:'zika',name:'Virus Zika',emoji:'🤰',risk:'medium',color:'#0ea5e9',cases:28000,deaths:12,mort:0.04,countries:18,r0:4.5,trend:5,cat:'Arbovirose',pathogen:'Flavivirus ZIKV',vector:'Aedes aegypti',transmission:'Piqûre Aedes, sexuel, fœtus',host:'Moustiques Aedes, primates',incub:'3–14 jours',regions:['Amériques trop.','Asie SE'],lat:0,lng:-50,desc:'Microcéphalie fœtale, Guillain-Barré. Pandémie 2015-16. Résurgence sporadique.',vaccine:{name:'mRNA-1893 Moderna',maker:'Moderna / NIH',eff:null,status:'Essais',approved:'Phase 2',note:'AUCUN vaccin.',link:'https://www.who.int/news-room/fact-sheets/detail/zika-virus'},econ:{direct:7,tour:18,agri:1,health:160,gdp:-0.3,jobs:140000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/zika-virus',t:'WHO'}]},
{id:'yellow_fever',name:'Fièvre Jaune',emoji:'🟡',risk:'medium',color:'#ca8a04',cases:8400,deaths:2520,mort:30.0,countries:12,r0:5.5,trend:6,cat:'Arbovirose',pathogen:'Flavivirus YFV',vector:'Aedes/Haemagogus',transmission:'Piqûre moustique',host:'Primates, moustiques',incub:'3–6 jours',regions:['Afrique sub.','Amériques trop.'],lat:-10,lng:-55,desc:'1 dose = vie entière. Carnet Jaune obligatoire certains pays.',vaccine:{name:'YF-VAX / Stamaril',maker:'Sanofi / Fiocruz',eff:99,status:'Disponible',approved:'Mondial — Carnet Jaune',note:'1 dose unique vie entière.',link:'https://www.who.int/news-room/fact-sheets/detail/yellow-fever'},econ:{direct:5,tour:22,agri:4,health:120,gdp:-0.6,jobs:95000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/yellow-fever',t:'WHO'}]},
{id:'lassa',name:'Fièvre de Lassa',emoji:'🐀',risk:'medium',color:'#b45309',cases:14000,deaths:2100,mort:15.0,countries:5,r0:1.3,trend:8,cat:'Arénavirus',pathogen:'Mammarenavirus lassaense',vector:'Rongeur Mastomys',transmission:'Contact excréments rongeur',host:'Mastomys natalensis',incub:'6–21 jours',regions:['Afrique Ouest'],lat:7,lng:5,desc:'100-300K infections/an. 80% asymptomatiques. Nigeria endémique.',vaccine:{name:'GEO-LM01 Phase 2',maker:'NIH/IAVI',eff:null,status:'Essais',approved:'Phase 1-2',note:'AUCUN vaccin. Ribavirine si <6j.',link:'https://www.who.int/news-room/fact-sheets/detail/lassa-fever'},econ:{direct:2,tour:3,agri:5,health:82,gdp:-0.4,jobs:42000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/lassa-fever',t:'WHO'}]},
{id:'mers',name:'MERS-CoV',emoji:'🐪',risk:'watch',color:'#854d0e',cases:2620,deaths:958,mort:36.6,countries:27,r0:0.7,trend:2,cat:'Coronavirus',pathogen:'MERS-CoV bétacoronavirus',vector:'Dromadaires',transmission:'Contact dromadaires',host:'Dromadaires',incub:'2–14 jours',regions:['Arabie Saoudite','Moyen-Orient'],lat:24,lng:45,desc:'36.6% mortalité hospitalisée. 80% Arabie Saoudite.',vaccine:{name:'ChAd63 MERS / mRNA-1415',maker:'Oxford / Moderna',eff:null,status:'Essais',approved:'Phase 1-2',note:'AUCUN vaccin.',link:'https://www.who.int/news-room/fact-sheets/detail/middle-east-respiratory-syndrome-coronavirus-(mers-cov)'},econ:{direct:3,tour:28,agri:6,health:180,gdp:-0.8,jobs:120000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/middle-east-respiratory-syndrome-coronavirus-(mers-cov)',t:'WHO'}]},
{id:'rabies',name:'Rage',emoji:'🐕',risk:'medium',color:'#7c3aed',cases:59000,deaths:59000,mort:99.9,countries:150,r0:1.3,trend:0,cat:'Lyssavirus',pathogen:'Lyssavirus rabies',vector:'Morsure animal',transmission:'Morsure/griffure',host:'Chiens 99%, chauves-souris',incub:'1–3 mois',regions:['Asie 56%','Afrique 44%'],lat:20,lng:80,desc:'100% mortel sans PEP. 100% évitable avec PEP. 99% cas chien.',vaccine:{name:'RABIPUR / RabAvert / VERORAB',maker:'GSK / Bavarian Nordic / Sanofi',eff:100,status:'Disponible',approved:'Mondial',note:'PEP: 4 doses + RIG J0.',link:'https://www.who.int/news-room/fact-sheets/detail/rabies'},econ:{direct:9,tour:3,agri:5,health:580,gdp:-0.2,jobs:85000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/rabies',t:'WHO'}]},
{id:'chikungunya',name:'Chikungunya',emoji:'🦟',risk:'medium',color:'#f472b6',cases:480000,deaths:480,mort:0.1,countries:46,r0:5.5,trend:15,cat:'Arbovirose',pathogen:'Alphavirus CHIKV',vector:'Aedes',transmission:'Piqûre Aedes',host:'Moustiques Aedes, primates',incub:'3–7 jours',regions:['Afrique','Asie','Europe','Amériques'],lat:5,lng:20,desc:'Arthralgie chronique. Premier vaccin mondial Ixchiq (FDA nov. 2023).',vaccine:{name:'Ixchiq (Valneva) / Vimkunya',maker:'Valneva / Bavarian Nordic',eff:84,status:'Disponible',approved:'FDA USA nov. 2023',note:'Dose unique SC ≥18 ans.',link:'https://www.who.int/news-room/fact-sheets/detail/chikungunya'},econ:{direct:6,tour:9,agri:2,health:240,gdp:-0.2,jobs:180000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/chikungunya',t:'WHO'}]},
{id:'hep_b',name:'Hépatite B',emoji:'🫀',risk:'high',color:'#d97706',cases:296000000,deaths:820000,mort:0.28,countries:195,r0:50,trend:-2,cat:'Hépadnavirus',pathogen:'VHB',vector:'Sang, sexuel, périnatal',transmission:'Sang, sexuel, mère-enfant',host:'Chimpanzés (expérimental)',incub:'30–180 jours',regions:['Mondial (Asie-Pacifique, Afrique)'],lat:35,lng:105,desc:'296M infections chroniques. 1ère cause cancer foie.',vaccine:{name:'Engerix-B / Recombivax',maker:'GSK / Merck',eff:95,status:'Disponible',approved:'Mondial 189 pays',note:'3 doses IM. 1ère <24h vie.',link:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-b'},econ:{direct:18,tour:3,agri:0,health:1800,gdp:-0.5,jobs:320000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-b',t:'WHO'}]},
{id:'polio',name:'Poliovirus cVDPV',emoji:'🦠',risk:'medium',color:'#0284c7',cases:420,deaths:21,mort:5.0,countries:15,r0:4.2,trend:12,cat:'Entérovirus',pathogen:'Poliovirus cVDPV2',vector:'Oro-fécale',transmission:'Eau/nourriture',host:'Réservoir humain',incub:'6–20 jours',regions:['Pakistan','Afghanistan','Nigeria','Ukraine'],lat:30,lng:65,desc:'PVS1 quasi-éradiqué. cVDPV sous-vaccinés. 1/200: paralysie irréversible.',vaccine:{name:'VPO / VPI / nOPV2',maker:'Sanofi / GSK',eff:99,status:'Disponible',approved:'Mondial 1955',note:'4 doses VPI.',link:'https://www.who.int/news-room/fact-sheets/detail/poliomyelitis'},econ:{direct:1.5,tour:3,agri:0,health:95,gdp:-0.2,jobs:45000},src:[{n:'GPEI',u:'https://polioeradication.org/',t:'ONU'}]},
{id:'meningitis',name:'Méningite bactérienne',emoji:'🧠',risk:'medium',color:'#7c2d12',cases:1200000,deaths:135000,mort:11.25,countries:180,r0:2.3,trend:5,cat:'Bactérie',pathogen:'Neisseria meningitidis ABCWY',vector:'Gouttelettes',transmission:'Gouttelettes, contacts rapprochés',host:'Réservoir humain',incub:'2–10 jours',regions:['Ceinture méningitique Afrique','Mondial'],lat:12,lng:5,desc:'Clone CC11(W) expansion mondiale. 50% mortalité sans traitement. Obligatoire Hajj.',vaccine:{name:'MenACWY / MenB / MenAFRIVAC',maker:'GSK / Pfizer / SII',eff:90,status:'Disponible',approved:'Mondial',note:'MenACWY obligatoire Hajj.',link:'https://www.who.int/news-room/fact-sheets/detail/meningitis'},econ:{direct:6,tour:3,agri:0,health:320,gdp:-0.3,jobs:95000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/meningitis',t:'WHO'}]},
{id:'rsv',name:'VRS (Bronchiolite)',emoji:'🫁',risk:'medium',color:'#0ea5e9',cases:64000000,deaths:160000,mort:0.25,countries:195,r0:3,trend:8,cat:'Pneumovirus',pathogen:'Virus respiratoire syncytial',vector:'Gouttelettes',transmission:'Gouttelettes, contact',host:'Humain',incub:'4–6 jours',regions:['Mondial'],lat:40,lng:0,desc:'Principale cause bronchiolite nourrissons. Vaccins Arexvy/Abrysvo récents.',vaccine:{name:'Arexvy / Abrysvo',maker:'GSK / Pfizer',eff:83,status:'Disponible',approved:'FDA 2023 (60+ ans, grossesse)',note:'Nirsevimab pour nourrissons.',link:'https://www.who.int/teams/health-product-policy-and-standards/standards-and-specifications/vaccine-standardization/respiratory-syncytial-virus-disease'},econ:{direct:15,tour:2,agri:0,health:680,gdp:-0.2,jobs:120000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/respiratory-syncytial-virus-(rsv)',t:'WHO'}]},
{id:'rotavirus',name:'Rotavirus',emoji:'💧',risk:'medium',color:'#06b6d4',cases:25000000,deaths:128000,mort:0.5,countries:195,r0:5,trend:-3,cat:'Rotavirus',pathogen:'Rotavirus A',vector:'Fécale-orale',transmission:'Fécale-orale',host:'Humain',incub:'1–3 jours',regions:['Afrique','Asie du Sud'],lat:10,lng:40,desc:'1ère cause diarrhée sévère enfants. Vaccins Rotarix/RotaTeq efficaces.',vaccine:{name:'Rotarix / RotaTeq',maker:'GSK / Merck',eff:85,status:'Disponible',approved:'Mondial GAVI',note:'2-3 doses orales nourrissons.',link:'https://www.who.int/news-room/fact-sheets/detail/rotavirus'},econ:{direct:8,tour:1,agri:0,health:340,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/teams/immunization-vaccines-and-biologicals/diseases/rotavirus',t:'WHO'}]},
{id:'typhoid',name:'Fièvre typhoïde',emoji:'🌡️',risk:'high',color:'#b45309',cases:11000000,deaths:110000,mort:1.0,countries:70,r0:2.8,trend:6,cat:'Bactérie',pathogen:'Salmonella Typhi',vector:'Eau/nourriture',transmission:'Fécale-orale',host:'Humain',incub:'6–30 jours',regions:['Asie du Sud','Afrique'],lat:20,lng:78,desc:'11M cas/an. Résistance XDR au Pakistan préoccupante.',vaccine:{name:'Typbar-TCV / Vi-PS',maker:'Bharat Biotech',eff:85,status:'Disponible',approved:'OMS préqualifiée',note:'Vaccin conjugué dès 6 mois.',link:'https://www.who.int/news-room/fact-sheets/detail/typhoid'},econ:{direct:6,tour:4,agri:2,health:280,gdp:-0.3,jobs:85000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/typhoid',t:'WHO'}]},
{id:'diphtheria',name:'Diphtérie',emoji:'😷',risk:'medium',color:'#7c2d12',cases:8400,deaths:2100,mort:25.0,countries:24,r0:6,trend:15,cat:'Bactérie',pathogen:'Corynebacterium diphtheriae',vector:'Gouttelettes',transmission:'Gouttelettes, contact',host:'Humain',incub:'2–5 jours',regions:['Afrique','Asie','Yémen'],lat:15,lng:45,desc:'Résurgence zones conflit. Nigeria épidémie 2023-24.',vaccine:{name:'DTC / DTaP',maker:'Multiples',eff:97,status:'Disponible',approved:'Mondial',note:'Combiné DTC, rappels.',link:'https://www.who.int/news-room/fact-sheets/detail/diphtheria'},econ:{direct:1,tour:1,agri:0,health:56,gdp:-0.05,jobs:12000},src:[{n:'OMS',u:'https://www.who.int/health-topics/diphtheria',t:'WHO'}]},
{id:'tetanus',name:'Tétanos',emoji:'🦠',risk:'medium',color:'#78350f',cases:73000,deaths:35000,mort:48.0,countries:120,r0:0,trend:-5,cat:'Bactérie',pathogen:'Clostridium tetani',vector:'Plaies',transmission:'Spores dans plaies',host:'Environnement (sol)',incub:'3–21 jours',regions:['Afrique','Asie du Sud'],lat:10,lng:30,desc:'Non contagieux. Tétanos néonatal mortel. Vaccin très efficace.',vaccine:{name:'DTC / Td / TT',maker:'Multiples',eff:99,status:'Disponible',approved:'Mondial',note:'Rappel tous les 10 ans.',link:'https://www.who.int/news-room/fact-sheets/detail/tetanus'},econ:{direct:1,tour:0,agri:0,health:78,gdp:-0.05,jobs:15000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/tetanus',t:'WHO'}]},
{id:'hepatitis_a',name:'Hépatite A',emoji:'🫀',risk:'medium',color:'#ca8a04',cases:159000000,deaths:39000,mort:0.025,countries:190,r0:2.5,trend:3,cat:'Hepatovirus',pathogen:'VHA',vector:'Eau/nourriture',transmission:'Fécale-orale',host:'Humain',incub:'15–50 jours',regions:['Afrique','Asie','Amérique latine'],lat:15,lng:20,desc:'159M cas/an. Épidémies liées eau contaminée.',vaccine:{name:'Havrix / Vaqta',maker:'GSK / Merck',eff:95,status:'Disponible',approved:'Mondial',note:'2 doses, immunité longue.',link:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-a'},econ:{direct:5,tour:6,agri:1,health:180,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-a',t:'WHO'}]},
{id:'hepatitis_c',name:'Hépatite C',emoji:'🫀',risk:'high',color:'#d97706',cases:50000000,deaths:242000,mort:0.48,countries:195,r0:2,trend:-4,cat:'Hepacivirus',pathogen:'VHC',vector:'Sang',transmission:'Sang, seringues',host:'Humain',incub:'14–180 jours',regions:['Mondial (Égypte, Asie centrale)'],lat:30,lng:60,desc:'50M infections chroniques. Curable à 95% avec antiviraux directs.',vaccine:{name:'Aucun vaccin — Sofosbuvir',maker:'Gilead',eff:null,status:'Aucun',approved:'Traitement AAD curatif 95%',note:'AUCUN vaccin. Curable.',link:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-c'},econ:{direct:14,tour:1,agri:0,health:1200,gdp:-0.3,jobs:180000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-c',t:'WHO'}]},
{id:'hepatitis_e',name:'Hépatite E',emoji:'🫀',risk:'medium',color:'#a16207',cases:20000000,deaths:44000,mort:0.22,countries:120,r0:2,trend:5,cat:'Hepevirus',pathogen:'VHE',vector:'Eau',transmission:'Fécale-orale',host:'Porcs, humain',incub:'15–60 jours',regions:['Asie','Afrique'],lat:20,lng:80,desc:'20M cas/an. Mortel femmes enceintes (20%).',vaccine:{name:'Hecolin (Chine)',maker:'Xiamen Innovax',eff:95,status:'Disponible',approved:'Chine uniquement',note:'Disponible seulement en Chine.',link:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-e'},econ:{direct:3,tour:2,agri:1,health:120,gdp:-0.1,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/hepatitis-e',t:'WHO'}]},
{id:'leishmaniasis',name:'Leishmaniose',emoji:'🦟',risk:'high',color:'#92400e',cases:1000000,deaths:26000,mort:2.6,countries:98,r0:0,trend:7,cat:'Parasite',pathogen:'Leishmania spp.',vector:'Phlébotome',transmission:'Piqûre phlébotome',host:'Chiens, rongeurs',incub:'2–6 mois',regions:['Moyen-Orient','Afrique','Amérique latine','Inde'],lat:25,lng:50,desc:'700K-1M cas/an. Forme viscérale (kala-azar) mortelle sans traitement.',vaccine:{name:'Aucun vaccin humain',maker:'—',eff:null,status:'Aucun',approved:'Amphotéricine B (traitement)',note:'AUCUN vaccin. Recherche en cours.',link:'https://www.who.int/news-room/fact-sheets/detail/leishmaniasis'},econ:{direct:4,tour:2,agri:3,health:180,gdp:-0.2,jobs:65000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/leishmaniasis',t:'WHO'}]},
{id:'schistosomiasis',name:'Schistosomiase',emoji:'🐌',risk:'high',color:'#166534',cases:251000000,deaths:200000,mort:0.08,countries:78,r0:0,trend:2,cat:'Parasite',pathogen:'Schistosoma spp.',vector:'Escargots aquatiques',transmission:'Contact eau douce',host:'Escargots',incub:'14–84 jours',regions:['Afrique sub.','Moyen-Orient','Amérique du Sud'],lat:0,lng:25,desc:'251M personnes nécessitent traitement. 90% en Afrique.',vaccine:{name:'Aucun — Praziquantel',maker:'—',eff:null,status:'Essais',approved:'Praziquantel (traitement)',note:'Vaccin Sh28GST Phase 3.',link:'https://www.who.int/news-room/fact-sheets/detail/schistosomiasis'},econ:{direct:6,tour:1,agri:8,health:280,gdp:-0.4,jobs:120000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/schistosomiasis',t:'WHO'}]},
{id:'lymphatic_filariasis',name:'Filariose lymphatique',emoji:'🦟',risk:'medium',color:'#15803d',cases:51000000,deaths:0,mort:0,countries:72,r0:0,trend:-8,cat:'Parasite',pathogen:'Wuchereria bancrofti',vector:'Moustiques',transmission:'Piqûre moustique',host:'Humain',incub:'Mois-années',regions:['Afrique','Asie du Sud-Est','Pacifique'],lat:5,lng:80,desc:'Éléphantiasis. 51M infectés. Programme élimination OMS.',vaccine:{name:'Aucun — Ivermectine+Albendazole',maker:'—',eff:null,status:'Aucun',approved:'Traitement de masse',note:'Élimination par traitement.',link:'https://www.who.int/news-room/fact-sheets/detail/lymphatic-filariasis'},econ:{direct:3,tour:1,agri:5,health:120,gdp:-0.3,jobs:85000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/lymphatic-filariasis',t:'WHO'}]},
{id:'onchocerciasis',name:'Onchocercose',emoji:'👁️',risk:'medium',color:'#14532d',cases:21000000,deaths:0,mort:0,countries:31,r0:0,trend:-6,cat:'Parasite',pathogen:'Onchocerca volvulus',vector:'Simulies',transmission:'Piqûre simulie',host:'Humain',incub:'Mois-années',regions:['Afrique sub.','Yémen','Amérique latine'],lat:8,lng:20,desc:'Cécité des rivières. 21M infectés, 99% en Afrique.',vaccine:{name:'Aucun — Ivermectine',maker:'Merck (don)',eff:null,status:'Aucun',approved:'Ivermectine annuelle',note:'Programme APOC.',link:'https://www.who.int/news-room/fact-sheets/detail/onchocerciasis'},econ:{direct:2,tour:1,agri:6,health:98,gdp:-0.3,jobs:65000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/onchocerciasis',t:'WHO'}]},
{id:'trachoma',name:'Trachome',emoji:'👁️',risk:'medium',color:'#166534',cases:1900000,deaths:0,mort:0,countries:44,r0:0,trend:-10,cat:'Bactérie',pathogen:'Chlamydia trachomatis',vector:'Mouches/contact',transmission:'Contact, mouches',host:'Humain',incub:'5–12 jours',regions:['Afrique','Moyen-Orient'],lat:12,lng:38,desc:'1ère cause cécité infectieuse. 1.9M personnes cécité/malvoyance.',vaccine:{name:'Aucun — Azithromycine',maker:'Pfizer (don)',eff:null,status:'Aucun',approved:'Stratégie SAFE',note:'Antibiotique + chirurgie.',link:'https://www.who.int/news-room/fact-sheets/detail/trachoma'},econ:{direct:1,tour:0,agri:2,health:56,gdp:-0.1,jobs:28000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/trachoma',t:'WHO'}]},
{id:'chagas',name:'Maladie de Chagas',emoji:'🪳',risk:'high',color:'#7f1d1d',cases:7000000,deaths:12000,mort:0.17,countries:21,r0:0,trend:1,cat:'Parasite',pathogen:'Trypanosoma cruzi',vector:'Triatomes',transmission:'Piqûre triatome, congénital',host:'Mammifères',incub:'1–2 semaines',regions:['Amérique latine'],lat:-15,lng:-60,desc:'6-7M infectés. Cardiomyopathie chronique mortelle.',vaccine:{name:'Aucun — Benznidazole',maker:'—',eff:null,status:'Aucun',approved:'Traitement phase aiguë',note:'AUCUN vaccin.',link:'https://www.who.int/news-room/fact-sheets/detail/chagas-disease-(american-trypanosomiasis)'},econ:{direct:7,tour:1,agri:2,health:280,gdp:-0.2,jobs:65000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/chagas-disease-(american-trypanosomiasis)',t:'WHO'}]},
{id:'sleeping_sickness',name:'Trypanosomiase africaine',emoji:'😴',risk:'medium',color:'#581c87',cases:800,deaths:200,mort:25.0,countries:36,r0:0,trend:-15,cat:'Parasite',pathogen:'Trypanosoma brucei',vector:'Mouche tsé-tsé',transmission:'Piqûre tsé-tsé',host:'Bétail, humain',incub:'Jours-semaines',regions:['Afrique sub.'],lat:-2,lng:22,desc:'Maladie du sommeil. Quasi-éliminée. RDC endémique.',vaccine:{name:'Aucun — Fexinidazole',maker:'DNDi',eff:null,status:'Aucun',approved:'Fexinidazole oral 2019',note:'Traitement oral révolutionnaire.',link:'https://www.who.int/news-room/fact-sheets/detail/trypanosomiasis-human-african-(sleeping-sickness)'},econ:{direct:1,tour:1,agri:4,health:45,gdp:-0.1,jobs:28000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/trypanosomiasis-human-african-(sleeping-sickness)',t:'WHO'}]},
{id:'buruli',name:'Ulcère de Buruli',emoji:'🩹',risk:'watch',color:'#78716c',cases:2000,deaths:0,mort:0,countries:33,r0:0,trend:3,cat:'Bactérie',pathogen:'Mycobacterium ulcerans',vector:'Inconnu (eau)',transmission:'Environnement aquatique',host:'Environnement',incub:'Semaines-mois',regions:['Afrique de l\'Ouest','Australie'],lat:6,lng:2,desc:'Ulcères cutanés destructeurs. Transmission mal comprise.',vaccine:{name:'Aucun — Antibiotiques',maker:'—',eff:null,status:'Aucun',approved:'Rifampicine+Clarithromycine',note:'BCG protection partielle.',link:'https://www.who.int/news-room/fact-sheets/detail/buruli-ulcer-(mycobacterium-ulcerans-infection)'},econ:{direct:0.5,tour:0,agri:1,health:28,gdp:-0.05,jobs:8000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/buruli-ulcer-(mycobacterium-ulcerans-infection)',t:'WHO'}]},
{id:'leprosy',name:'Lèpre',emoji:'🖐️',risk:'medium',color:'#57534e',cases:200000,deaths:0,mort:0,countries:120,r0:0,trend:0,cat:'Bactérie',pathogen:'Mycobacterium leprae',vector:'Gouttelettes',transmission:'Gouttelettes prolongées',host:'Humain, tatous',incub:'2–20 ans',regions:['Inde','Brésil','Indonésie'],lat:20,lng:78,desc:'200K nouveaux cas/an. Inde 60% des cas. Curable.',vaccine:{name:'BCG (partiel) — PCT',maker:'—',eff:50,status:'Disponible',approved:'Polychimiothérapie (traitement)',note:'PCT gratuite OMS depuis 1995.',link:'https://www.who.int/news-room/fact-sheets/detail/leprosy'},econ:{direct:2,tour:0,agri:1,health:98,gdp:-0.1,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/leprosy',t:'WHO'}]},
{id:'guinea_worm',name:'Dracunculose',emoji:'🪱',risk:'watch',color:'#166534',cases:14,deaths:0,mort:0,countries:5,r0:0,trend:-20,cat:'Parasite',pathogen:'Dracunculus medinensis',vector:'Copépodes (eau)',transmission:'Eau contaminée',host:'Humain, chiens',incub:'10–14 mois',regions:['Tchad','Sud-Soudan','Mali','Éthiopie'],lat:12,lng:20,desc:'Ver de Guinée. Quasi-éradiqué: 14 cas en 2023 (vs 3.5M en 1986).',vaccine:{name:'Aucun — Filtration eau',maker:'Carter Center',eff:null,status:'Aucun',approved:'Prévention par filtration',note:'Éradication imminente.',link:'https://www.who.int/news-room/fact-sheets/detail/dracunculiasis-(guinea-worm-disease)'},econ:{direct:0.1,tour:0,agri:1,health:12,gdp:-0.02,jobs:2000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/dracunculiasis-(guinea-worm-disease)',t:'WHO'}]},
{id:'west_nile',name:'Virus du Nil occidental',emoji:'🦟',risk:'medium',color:'#a16207',cases:2000,deaths:180,mort:9.0,countries:65,r0:0,trend:8,cat:'Arbovirose',pathogen:'Flavivirus VNO',vector:'Moustiques Culex',transmission:'Piqûre Culex',host:'Oiseaux',incub:'2–14 jours',regions:['USA','Europe','Afrique','Moyen-Orient'],lat:38,lng:-95,desc:'Encéphalite. Recrudescence USA/Europe été. Oiseaux réservoirs.',vaccine:{name:'Aucun vaccin humain',maker:'—',eff:null,status:'Aucun',approved:'Soins de soutien',note:'Vaccin équin existe.',link:'https://www.who.int/news-room/fact-sheets/detail/west-nile-virus'},econ:{direct:2,tour:3,agri:2,health:120,gdp:-0.1,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/west-nile-virus',t:'WHO'}]},
{id:'japanese_encephalitis',name:'Encéphalite japonaise',emoji:'🧠',risk:'high',color:'#7c2d12',cases:68000,deaths:17000,mort:25.0,countries:24,r0:0,trend:2,cat:'Arbovirose',pathogen:'Flavivirus EJ',vector:'Moustiques Culex',transmission:'Piqûre Culex',host:'Porcs, oiseaux',incub:'5–15 jours',regions:['Asie','Pacifique occidental'],lat:20,lng:100,desc:'68K cas/an. 1ère cause encéphalite virale Asie. Vaccin efficace.',vaccine:{name:'Ixiaro / SA 14-14-2',maker:'Valneva',eff:95,status:'Disponible',approved:'Mondial',note:'Vaccin recommandé Asie.',link:'https://www.who.int/news-room/fact-sheets/detail/japanese-encephalitis'},econ:{direct:3,tour:5,agri:4,health:180,gdp:-0.2,jobs:56000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/japanese-encephalitis',t:'WHO'}]},
{id:'crimean_congo',name:'Fièvre Crimée-Congo',emoji:'🩸',risk:'high',color:'#991b1b',cases:15000,deaths:4500,mort:30.0,countries:52,r0:1.1,trend:6,cat:'Nairovirus',pathogen:'Virus FHCC',vector:'Tiques Hyalomma',transmission:'Piqûre tique, sang',host:'Bétail, tiques',incub:'1–13 jours',regions:['Afrique','Balkans','Moyen-Orient','Asie'],lat:35,lng:45,desc:'Fièvre hémorragique. PRIORITÉ OMS. Mortalité jusqu\'à 40%.',vaccine:{name:'Aucun vaccin approuvé',maker:'—',eff:null,status:'Essais',approved:'Ribavirine (débattu)',note:'Vaccins en Phase 1.',link:'https://www.who.int/news-room/fact-sheets/detail/crimean-congo-haemorrhagic-fever'},econ:{direct:1,tour:2,agri:6,health:78,gdp:-0.1,jobs:28000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/crimean-congo-haemorrhagic-fever',t:'WHO'}]},
{id:'rift_valley',name:'Fièvre de la Vallée du Rift',emoji:'🐑',risk:'high',color:'#b45309',cases:8000,deaths:800,mort:10.0,countries:35,r0:0,trend:5,cat:'Phlébovirus',pathogen:'Virus FVR',vector:'Moustiques',transmission:'Piqûre, contact animaux',host:'Bétail',incub:'2–6 jours',regions:['Afrique','Péninsule arabique'],lat:0,lng:35,desc:'Zoonose. Épidémies liées pluies. Impact bétail majeur.',vaccine:{name:'Aucun vaccin humain',maker:'—',eff:null,status:'Essais',approved:'Vaccin vétérinaire existe',note:'Vaccins humains Phase 1.',link:'https://www.who.int/news-room/fact-sheets/detail/rift-valley-fever'},econ:{direct:2,tour:2,agri:12,health:78,gdp:-0.2,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/rift-valley-fever',t:'WHO'}]},
{id:'plague',name:'Peste',emoji:'🐀',risk:'high',color:'#450a0a',cases:600,deaths:120,mort:20.0,countries:26,r0:1.3,trend:3,cat:'Bactérie',pathogen:'Yersinia pestis',vector:'Puces',transmission:'Puces, gouttelettes (pulmonaire)',host:'Rongeurs',incub:'1–7 jours',regions:['Madagascar','RD Congo','Pérou','USA'],lat:-18,lng:47,desc:'Madagascar 75% des cas mondiaux. Peste pulmonaire mortelle rapidement.',vaccine:{name:'Aucun vaccin large — Antibiotiques',maker:'—',eff:null,status:'Essais',approved:'Streptomycine/Gentamicine',note:'Curable si traité tôt.',link:'https://www.who.int/news-room/fact-sheets/detail/plague'},econ:{direct:1,tour:4,agri:2,health:56,gdp:-0.1,jobs:18000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/plague',t:'WHO'}]},
{id:'anthrax',name:'Anthrax (Charbon)',emoji:'🦠',risk:'medium',color:'#3f3f46',cases:2000,deaths:400,mort:20.0,countries:40,r0:0,trend:2,cat:'Bactérie',pathogen:'Bacillus anthracis',vector:'Spores/animaux',transmission:'Contact animaux, spores',host:'Bétail',incub:'1–7 jours',regions:['Afrique','Asie centrale'],lat:10,lng:30,desc:'Zoonose. Bioterrorisme potentiel. Formes cutanée/pulmonaire/digestive.',vaccine:{name:'BioThrax (AVA)',maker:'Emergent BioSolutions',eff:92,status:'Disponible',approved:'USA (militaires, à risque)',note:'Vaccin + antibiotiques.',link:'https://www.who.int/news-room/fact-sheets/detail/anthrax'},econ:{direct:1,tour:0,agri:4,health:45,gdp:-0.05,jobs:12000},src:[{n:'OMS',u:'https://www.who.int/health-topics/anthrax',t:'WHO'}]},
{id:'brucellosis',name:'Brucellose',emoji:'🐄',risk:'medium',color:'#78716c',cases:500000,deaths:2000,mort:0.4,countries:100,r0:0,trend:2,cat:'Bactérie',pathogen:'Brucella spp.',vector:'Produits laitiers/animaux',transmission:'Lait cru, contact animaux',host:'Bétail',incub:'1–8 semaines',regions:['Méditerranée','Moyen-Orient','Asie centrale'],lat:35,lng:40,desc:'500K cas/an. Fièvre de Malte. Liée élevage.',vaccine:{name:'Aucun vaccin humain',maker:'—',eff:null,status:'Aucun',approved:'Doxycycline+Rifampicine',note:'Vaccins vétérinaires.',link:'https://www.who.int/news-room/fact-sheets/detail/brucellosis'},econ:{direct:3,tour:1,agri:8,health:120,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/brucellosis',t:'WHO'}]},
{id:'leptospirosis',name:'Leptospirose',emoji:'🐀',risk:'medium',color:'#0f766e',cases:1030000,deaths:59000,mort:5.7,countries:100,r0:0,trend:6,cat:'Bactérie',pathogen:'Leptospira spp.',vector:'Eau/urine animaux',transmission:'Eau contaminée urine',host:'Rongeurs, bétail',incub:'2–30 jours',regions:['Tropiques','Asie du Sud-Est'],lat:5,lng:100,desc:'1M cas/an. Épidémies après inondations. Maladie de Weil grave.',vaccine:{name:'Aucun vaccin large',maker:'—',eff:null,status:'Aucun',approved:'Doxycycline/Pénicilline',note:'Vaccins locaux limités.',link:'https://www.who.int/news-room/fact-sheets/detail/leptospirosis'},econ:{direct:3,tour:2,agri:6,health:180,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/health-topics/leptospirosis',t:'WHO'}]},
{id:'melioidosis',name:'Mélioïdose',emoji:'🦠',risk:'medium',color:'#166534',cases:165000,deaths:89000,mort:54.0,countries:45,r0:0,trend:4,cat:'Bactérie',pathogen:'Burkholderia pseudomallei',vector:'Sol/eau',transmission:'Contact sol, inhalation',host:'Environnement',incub:'1–21 jours',regions:['Asie du Sud-Est','Australie du Nord'],lat:15,lng:100,desc:'165K cas/an. Sous-diagnostiquée. Mortalité élevée. Sol tropical.',vaccine:{name:'Aucun vaccin',maker:'—',eff:null,status:'Essais',approved:'Ceftazidime (traitement)',note:'AUCUN vaccin. Recherche.',link:'https://www.who.int/news-room/fact-sheets/detail/melioidosis'},econ:{direct:2,tour:1,agri:3,health:180,gdp:-0.1,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/health-topics/melioidosis',t:'WHO'}]},
{id:'scrub_typhus',name:'Typhus des broussailles',emoji:'🦟',risk:'medium',color:'#a16207',cases:1000000,deaths:35000,mort:3.5,countries:20,r0:0,trend:5,cat:'Bactérie',pathogen:'Orientia tsutsugamushi',vector:'Acariens (larves)',transmission:'Piqûre acarien',host:'Rongeurs',incub:'6–21 jours',regions:['Asie-Pacifique (triangle tsutsugamushi)'],lat:20,lng:110,desc:'1M cas/an. Zone Asie-Pacifique. Escarre caractéristique.',vaccine:{name:'Aucun vaccin — Doxycycline',maker:'—',eff:null,status:'Aucun',approved:'Doxycycline efficace',note:'AUCUN vaccin.',link:'https://www.who.int/southeastasia/health-topics/scrub-typhus'},econ:{direct:2,tour:1,agri:3,health:120,gdp:-0.1,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/southeastasia/health-topics/scrub-typhus',t:'WHO'}]},
{id:'norovirus',name:'Norovirus',emoji:'🤮',risk:'medium',color:'#0891b2',cases:685000000,deaths:200000,mort:0.03,countries:195,r0:2.6,trend:4,cat:'Calicivirus',pathogen:'Norovirus',vector:'Fécale-orale',transmission:'Fécale-orale, surfaces',host:'Humain',incub:'12–48h',regions:['Mondial'],lat:40,lng:0,desc:'685M cas/an. Gastro hivernale. Épidémies croisières/hôpitaux.',vaccine:{name:'Aucun — Essais Moderna',maker:'Moderna',eff:null,status:'Essais',approved:'Soins de soutien',note:'mRNA-1403 Phase 3.',link:'https://www.who.int/news-room/fact-sheets/detail/foodborne-diseases'},econ:{direct:12,tour:8,agri:2,health:340,gdp:-0.1,jobs:85000},src:[{n:'CDC',u:'https://www.cdc.gov/norovirus/',t:'CDC'}]},
{id:'group_a_strep',name:'Streptocoque A invasif',emoji:'🦠',risk:'high',color:'#dc2626',cases:750000,deaths:160000,mort:21.0,countries:195,r0:2,trend:18,cat:'Bactérie',pathogen:'Streptococcus pyogenes',vector:'Gouttelettes',transmission:'Gouttelettes, contact',host:'Humain',incub:'1–3 jours',regions:['Mondial'],lat:45,lng:0,desc:'Résurgence iGAS 2023-2024. Fasciite nécrosante, choc toxique.',vaccine:{name:'Aucun — Essais Phase 1',maker:'Multiples',eff:null,status:'Essais',approved:'Pénicilline efficace',note:'Vaccins 30-valents en essais.',link:'https://www.who.int/news-room/fact-sheets/detail/streptococcus'},econ:{direct:6,tour:1,agri:0,health:340,gdp:-0.1,jobs:65000},src:[{n:'OMS',u:'https://www.who.int/teams/immunization-vaccines-and-biologicals/diseases/group-a-streptococcus',t:'WHO'}]},
{id:'pneumococcus',name:'Pneumocoque',emoji:'🫁',risk:'high',color:'#0369a1',cases:14500000,deaths:1189000,mort:8.2,countries:195,r0:2,trend:1,cat:'Bactérie',pathogen:'Streptococcus pneumoniae',vector:'Gouttelettes',transmission:'Gouttelettes',host:'Humain',incub:'1–3 jours',regions:['Mondial'],lat:20,lng:20,desc:'1ère cause pneumonie mortelle enfants. Vaccins conjugués efficaces.',vaccine:{name:'Prevnar 20 / PCV13 / PPSV23',maker:'Pfizer / Merck',eff:75,status:'Disponible',approved:'Mondial',note:'PCV nourrissons + 65 ans.',link:'https://www.who.int/news-room/fact-sheets/detail/pneumonia'},econ:{direct:18,tour:2,agri:0,health:1200,gdp:-0.3,jobs:180000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/pneumonia',t:'WHO'}]},
{id:'hib',name:'Haemophilus influenzae b',emoji:'🦠',risk:'medium',color:'#0e7490',cases:8000000,deaths:340000,mort:4.3,countries:190,r0:0,trend:-5,cat:'Bactérie',pathogen:'Haemophilus influenzae type b',vector:'Gouttelettes',transmission:'Gouttelettes',host:'Humain',incub:'2–4 jours',regions:['Afrique','Asie du Sud'],lat:15,lng:60,desc:'Méningite/pneumonie enfants. Vaccin Hib très efficace.',vaccine:{name:'Hib / Pentavalent',maker:'Multiples',eff:95,status:'Disponible',approved:'Mondial GAVI',note:'Inclus vaccin pentavalent.',link:'https://www.who.int/teams/immunization-vaccines-and-biologicals/diseases/haemophilus-influenzae-type-b'},econ:{direct:4,tour:0,agri:0,health:280,gdp:-0.1,jobs:56000},src:[{n:'OMS',u:'https://www.who.int/teams/immunization-vaccines-and-biologicals/diseases/haemophilus-influenzae-type-b',t:'WHO'}]},
{id:'hpv',name:'Papillomavirus (HPV)',emoji:'🎗️',risk:'high',color:'#be185d',cases:625000,deaths:342000,mort:54.7,countries:195,r0:0,trend:-3,cat:'Papillomavirus',pathogen:'HPV 16/18',vector:'Sexuel',transmission:'Contact sexuel',host:'Humain',incub:'Mois-années',regions:['Mondial (Afrique sub. cancer col)'],lat:0,lng:20,desc:'1ère cause cancer du col. Vaccin peut éliminer la maladie.',vaccine:{name:'Gardasil 9 / Cervarix',maker:'Merck / GSK',eff:90,status:'Disponible',approved:'Mondial',note:'2 doses filles 9-14 ans.',link:'https://www.who.int/news-room/fact-sheets/detail/human-papillomavirus-(hpv)-and-cervical-cancer'},econ:{direct:16,tour:1,agri:0,health:1400,gdp:-0.3,jobs:180000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/cervical-cancer',t:'WHO'}]},
{id:'oropouche',name:'Fièvre Oropouche',emoji:'🦟',risk:'medium',color:'#ea580c',cases:12000,deaths:2,mort:0.02,countries:8,r0:0,trend:35,cat:'Orthobunyavirus',pathogen:'Virus Oropouche',vector:'Moucherons Culicoides',transmission:'Piqûre moucheron',host:'Paresseux, oiseaux',incub:'4–8 jours',regions:['Amazonie','Amérique latine','Caraïbes'],lat:-5,lng:-65,desc:'🚨 Émergence 2024. Brésil, Cuba. Transmission verticale suspectée.',vaccine:{name:'Aucun vaccin',maker:'—',eff:null,status:'Aucun',approved:'Soins de soutien',note:'AUCUN vaccin. Surveillance.',link:'https://www.who.int/emergencies/disease-outbreak-news'},econ:{direct:1,tour:3,agri:1,health:45,gdp:-0.1,jobs:18000},src:[{n:'OMS',u:'https://www.who.int/emergencies/disease-outbreak-news',t:'WHO'}]},
{id:'enterovirus_d68',name:'Entérovirus D68',emoji:'🫁',risk:'medium',color:'#7c3aed',cases:45000,deaths:200,mort:0.4,countries:40,r0:0,trend:12,cat:'Entérovirus',pathogen:'Enterovirus D68',vector:'Respiratoire',transmission:'Gouttelettes, contact',host:'Humain',incub:'3–5 jours',regions:['USA','Europe','Asie'],lat:40,lng:-95,desc:'Paralysie flasque aiguë (myélite) chez enfants. Pics cycliques.',vaccine:{name:'Aucun vaccin',maker:'—',eff:null,status:'Aucun',approved:'Soins de soutien',note:'AUCUN vaccin ni traitement.',link:'https://www.cdc.gov/enterovirus-d68/'},econ:{direct:1,tour:0,agri:0,health:56,gdp:-0.05,jobs:12000},src:[{n:'CDC',u:'https://www.cdc.gov/enterovirus-d68/',t:'CDC'}]},
{id:'acute_hepatitis_unknown',name:'Hépatite aiguë inconnue',emoji:'🫀',risk:'watch',color:'#b45309',cases:1010,deaths:22,mort:2.2,countries:35,r0:0,trend:0,cat:'Inconnu',pathogen:'Adénovirus 41 suspecté',vector:'Inconnu',transmission:'Inconnue',host:'Inconnu',incub:'Inconnue',regions:['Mondial (2022-2023)'],lat:50,lng:0,desc:'Mystère 2022: hépatites sévères enfants. Adénovirus/AAV2 suspectés.',vaccine:{name:'Aucun — cause inconnue',maker:'—',eff:null,status:'Aucun',approved:'Soins de soutien/greffe',note:'Investigation OMS en cours.',link:'https://www.who.int/emergencies/disease-outbreak-news'},econ:{direct:0.5,tour:0,agri:0,health:34,gdp:-0.02,jobs:5000},src:[{n:'OMS',u:'https://www.who.int/emergencies/disease-outbreak-news',t:'WHO'}]},
{id:'disease_x',name:'Maladie X (inconnue)',emoji:'❓',risk:'watch',color:'#6b7280',cases:0,deaths:0,mort:0,countries:0,r0:0,trend:0,cat:'Hypothétique',pathogen:'Pathogène inconnu (Blueprint OMS)',vector:'Inconnu',transmission:'Inconnue',host:'Inconnu',incub:'Inconnue',regions:['Potentiellement mondial'],lat:0,lng:0,desc:'Concept OMS: prochaine pandémie inconnue. Préparation CEPI 100 jours.',vaccine:{name:'Plateforme ARNm prête',maker:'CEPI',eff:null,status:'Essais',approved:'Préparation 100 jours',note:'Vaccins prototypes prêts.',link:'https://www.who.int/news-room/questions-and-answers/item/disease-x'},econ:{direct:0,tour:0,agri:0,health:0,gdp:0,jobs:0},src:[{n:'OMS',u:'https://www.who.int/news-room/questions-and-answers/item/disease-x',t:'WHO'}]},
{id:'legionnaires',name:'Légionellose',emoji:'💧',risk:'medium',color:'#0891b2',cases:8000,deaths:800,mort:10.0,countries:60,r0:0,trend:3,cat:'Bactérie',pathogen:'Legionella pneumophila',vector:'Eau/aérosols',transmission:'Inhalation gouttelettes eau contaminée',host:'Aucun (environnement)',incub:'2–10 jours',regions:['Mondial'],lat:40,lng:-74,desc:'Pneumonie sévère. Systèmes de climatisation, tours de refroidissement. Épidémies urbaines.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Traitement antibiotique (azithromycine).',link:'https://www.who.int/news-room/fact-sheets/detail/legionellosis'},econ:{direct:2,tour:1,agri:0,health:80,gdp:-0.02,jobs:5000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/legionellosis',t:'WHO'}]},
{id:'botulism',name:'Botulisme',emoji:'🥫',risk:'medium',color:'#a16207',cases:1000,deaths:50,mort:5.0,countries:80,r0:0,trend:0,cat:'Bactérie/Toxine',pathogen:'Clostridium botulinum',vector:'Aliments/plaies',transmission:'Ingestion toxine (conserves), blessures',host:'Aucun (environnement)',incub:'12–72 heures',regions:['Mondial'],lat:40,lng:0,desc:'Intoxication neuroparalytique grave. Conserves mal stérilisées, miel (nourrissons). Paralysie flasque.',vaccine:{name:'Antitoxine',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Antitoxine botulique + soins intensifs.',link:'https://www.who.int/news-room/fact-sheets/detail/botulism'},econ:{direct:1,tour:0,agri:2,health:30,gdp:-0.01,jobs:2000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/botulism',t:'WHO'}]},
{id:'salmonellosis',name:'Salmonellose',emoji:'🍗',risk:'medium',color:'#ca8a04',cases:95000000,deaths:155000,mort:0.16,countries:195,r0:0,trend:1,cat:'Bactérie',pathogen:'Salmonella (non-typhi)',vector:'Aliments',transmission:'Aliments contaminés (œufs, volaille, viande)',host:'Animaux/volaille',incub:'6 heures–6 jours',regions:['Mondial'],lat:20,lng:0,desc:'Gastro-entérite. Une des principales causes de maladies d\'origine alimentaire mondiale. Épidémies fréquentes.',vaccine:{name:'Aucun (humain)',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Réhydratation, antibiotiques si sévère.',link:'https://www.who.int/news-room/fact-sheets/detail/salmonella-(non-typhoidal)'},econ:{direct:3,tour:2,agri:8,health:120,gdp:-0.08,jobs:25000},src:[{n:'OMS',u:'https://www.who.int/news-room/fact-sheets/detail/salmonella-(non-typhoidal)',t:'WHO'}]}
,
{id:'shigellosis',name:'Shigellose',emoji:'🚽',risk:'medium',color:'#a16207',cases:165000000,deaths:210000,mort:0.13,countries:150,r0:0,trend:2,cat:'Bactérie',pathogen:'Shigella spp.',vector:'Féco-oral',transmission:'Eau/aliments contaminés',host:'Humain',incub:'1–3 jours',regions:['Asie','Afrique'],lat:20,lng:80,desc:'Dysenterie bacillaire. Diarrhée sanglante. Résistance antibiotique croissante.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Réhydratation, antibiotiques.',link:'https://www.who.int/'},econ:{direct:4,tour:2,agri:1,health:180,gdp:-0.1,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'campylobacteriosis',name:'Campylobactériose',emoji:'🍖',risk:'medium',color:'#ca8a04',cases:96000000,deaths:21000,mort:0.02,countries:180,r0:0,trend:3,cat:'Bactérie',pathogen:'Campylobacter jejuni',vector:'Aliments',transmission:'Volaille, lait cru',host:'Volaille/bétail',incub:'2–5 jours',regions:['Mondial'],lat:30,lng:0,desc:'Première cause bactérienne de diarrhée. Volaille mal cuite. Syndrome Guillain-Barré possible.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Réhydratation.',link:'https://www.who.int/'},econ:{direct:5,tour:3,agri:6,health:220,gdp:-0.1,jobs:55000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'giardiasis',name:'Giardiase',emoji:'💧',risk:'medium',color:'#0891b2',cases:280000000,deaths:5000,mort:0.002,countries:180,r0:0,trend:1,cat:'Parasite',pathogen:'Giardia lamblia',vector:'Eau',transmission:'Eau contaminée',host:'Humain/animaux',incub:'1–3 semaines',regions:['Mondial'],lat:20,lng:20,desc:'Parasitose intestinale. Eau non traitée. Diarrhée chronique.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Métronidazole.',link:'https://www.who.int/'},econ:{direct:3,tour:2,agri:1,health:120,gdp:-0.05,jobs:25000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'cryptosporidiosis',name:'Cryptosporidiose',emoji:'💧',risk:'medium',color:'#0891b2',cases:64000000,deaths:48000,mort:0.075,countries:150,r0:0,trend:2,cat:'Parasite',pathogen:'Cryptosporidium',vector:'Eau',transmission:'Eau contaminée',host:'Humain/bétail',incub:'2–10 jours',regions:['Afrique','Asie'],lat:10,lng:30,desc:'Diarrhée aqueuse. Grave chez immunodéprimés et enfants. Résistant au chlore.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Nitazoxanide.',link:'https://www.who.int/'},econ:{direct:2,tour:1,agri:2,health:140,gdp:-0.08,jobs:30000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'amoebiasis',name:'Amibiase',emoji:'🦠',risk:'medium',color:'#a16207',cases:50000000,deaths:55000,mort:0.11,countries:140,r0:0,trend:1,cat:'Parasite',pathogen:'Entamoeba histolytica',vector:'Féco-oral',transmission:'Eau/aliments',host:'Humain',incub:'2–4 semaines',regions:['Asie','Afrique','Amérique latine'],lat:15,lng:40,desc:'Dysenterie amibienne. Abcès hépatiques possibles. Zones tropicales.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Métronidazole.',link:'https://www.who.int/'},econ:{direct:3,tour:2,agri:0,health:150,gdp:-0.06,jobs:35000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'ascariasis',name:'Ascaridiase',emoji:'🪱',risk:'medium',color:'#84cc16',cases:800000000,deaths:2000,mort:0.0003,countries:150,r0:0,trend:-2,cat:'Helminthe',pathogen:'Ascaris lumbricoides',vector:'Sol',transmission:'Œufs dans sol/aliments',host:'Humain',incub:'2–3 mois',regions:['Afrique','Asie','Amérique latine'],lat:10,lng:30,desc:'Ver rond intestinal. Plus commune des helminthiases. Retard croissance enfants.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Albendazole. Déparasitage de masse.',link:'https://www.who.int/'},econ:{direct:2,tour:0,agri:1,health:180,gdp:-0.1,jobs:40000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'hookworm',name:'Ankylostomiase',emoji:'🪱',risk:'medium',color:'#84cc16',cases:470000000,deaths:3000,mort:0.0006,countries:120,r0:0,trend:-3,cat:'Helminthe',pathogen:'Necator/Ancylostoma',vector:'Sol',transmission:'Larves pénètrent la peau',host:'Humain',incub:'variable',regions:['Afrique','Asie'],lat:5,lng:35,desc:'Ver intestinal. Anémie ferriprive. Contact sol contaminé pieds nus.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Albendazole.',link:'https://www.who.int/'},econ:{direct:2,tour:0,agri:2,health:120,gdp:-0.08,jobs:35000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'trichuriasis',name:'Trichocéphalose',emoji:'🪱',risk:'medium',color:'#84cc16',cases:460000000,deaths:1600,mort:0.0003,countries:120,r0:0,trend:-2,cat:'Helminthe',pathogen:'Trichuris trichiura',vector:'Sol',transmission:'Œufs dans sol',host:'Humain',incub:'variable',regions:['Afrique','Asie','Amérique latine'],lat:10,lng:30,desc:'Ver fouet. Diarrhée chronique. Co-infection fréquente avec ascaris.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Albendazole/mébendazole.',link:'https://www.who.int/'},econ:{direct:1,tour:0,agri:1,health:100,gdp:-0.06,jobs:28000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'taeniasis',name:'Téniase/Cysticercose',emoji:'🪱',risk:'medium',color:'#84cc16',cases:50000000,deaths:28000,mort:0.056,countries:100,r0:0,trend:0,cat:'Helminthe',pathogen:'Taenia solium',vector:'Porc',transmission:'Viande de porc mal cuite',host:'Porc/humain',incub:'8 semaines',regions:['Afrique','Asie','Amérique latine'],lat:5,lng:20,desc:'Ver solitaire. Neurocysticercose = cause majeure d\'épilepsie acquise.',vaccine:{name:'Vétérinaire',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Praziquantel.',link:'https://www.who.int/'},econ:{direct:2,tour:0,agri:3,health:160,gdp:-0.09,jobs:32000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'echinococcosis',name:'Échinococcose',emoji:'🐕',risk:'medium',color:'#84cc16',cases:1000000,deaths:19000,mort:1.9,countries:100,r0:0,trend:1,cat:'Helminthe',pathogen:'Echinococcus',vector:'Chiens',transmission:'Œufs via chiens/bétail',host:'Chiens/moutons',incub:'mois à années',regions:['Asie centrale','Afrique','Amérique du Sud'],lat:40,lng:60,desc:'Kystes hydatiques (foie, poumons). Zoonose. Chirurgie souvent nécessaire.',vaccine:{name:'Vétérinaire (EG95)',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Albendazole + chirurgie.',link:'https://www.who.int/'},econ:{direct:2,tour:0,agri:4,health:140,gdp:-0.05,jobs:22000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]}
,
{id:'adenovirus',name:'Adénovirus',emoji:'🫁',risk:'medium',color:'#6366f1',cases:50000000,deaths:15000,mort:0.03,countries:195,r0:2.5,trend:5,cat:'Virus',pathogen:'Adenovirus',vector:'Respiratoire',transmission:'Gouttelettes, contact',host:'Humain',incub:'2–14 jours',regions:['Mondial'],lat:30,lng:0,desc:'Infections respiratoires, conjonctivite, gastro. Épidémies en collectivités.',vaccine:{name:'Militaire (types 4,7)',maker:'—',eff:0,status:'Disponible',approved:'USA militaire',note:'Symptomatique.',link:'https://www.who.int/'},econ:{direct:6,tour:2,agri:0,health:280,gdp:-0.1,jobs:60000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'parainfluenza',name:'Parainfluenza',emoji:'🫁',risk:'medium',color:'#6366f1',cases:40000000,deaths:12000,mort:0.03,countries:195,r0:2,trend:3,cat:'Virus',pathogen:'HPIV 1-4',vector:'Respiratoire',transmission:'Gouttelettes',host:'Humain',incub:'2–6 jours',regions:['Mondial'],lat:30,lng:0,desc:'Laryngite, bronchiolite chez enfants. Cause majeure de croup.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Symptomatique.',link:'https://www.who.int/'},econ:{direct:4,tour:1,agri:0,health:190,gdp:-0.06,jobs:40000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'metapneumovirus',name:'Métapneumovirus',emoji:'🫁',risk:'medium',color:'#6366f1',cases:30000000,deaths:10000,mort:0.03,countries:195,r0:2,trend:4,cat:'Virus',pathogen:'hMPV',vector:'Respiratoire',transmission:'Gouttelettes',host:'Humain',incub:'3–6 jours',regions:['Mondial'],lat:30,lng:0,desc:'Infections respiratoires similaires au VRS. Enfants et personnes âgées.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Symptomatique.',link:'https://www.who.int/'},econ:{direct:3,tour:1,agri:0,health:160,gdp:-0.05,jobs:35000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'coxsackie',name:'Coxsackie (Pieds-mains-bouche)',emoji:'👣',risk:'medium',color:'#f59e0b',cases:20000000,deaths:2000,mort:0.01,countries:180,r0:5,trend:6,cat:'Virus',pathogen:'Coxsackievirus A16/EV71',vector:'Contact',transmission:'Féco-oral, gouttelettes',host:'Humain',incub:'3–6 jours',regions:['Asie','Mondial'],lat:20,lng:100,desc:'Syndrome pieds-mains-bouche. Enfants <5 ans. Épidémies en Asie (EV71 grave).',vaccine:{name:'EV71 (Chine)',maker:'Sinovac',eff:97,status:'Disponible',approved:'Chine',note:'Vaccin EV71 en Chine.',link:'https://www.who.int/'},econ:{direct:3,tour:2,agri:0,health:120,gdp:-0.05,jobs:30000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'parvovirus_b19',name:'Parvovirus B19 (5e maladie)',emoji:'🔴',risk:'medium',color:'#ef4444',cases:15000000,deaths:500,mort:0.003,countries:195,r0:1.5,trend:8,cat:'Virus',pathogen:'Parvovirus B19',vector:'Respiratoire',transmission:'Gouttelettes, sang',host:'Humain',incub:'4–14 jours',regions:['Mondial'],lat:40,lng:0,desc:'Mégalérythème épidémique. Danger grossesse (anémie fœtale). Résurgence 2024.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Symptomatique.',link:'https://www.who.int/'},econ:{direct:2,tour:0,agri:0,health:90,gdp:-0.02,jobs:15000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'epstein_barr',name:'Épstein-Barr (Mononucléose)',emoji:'🫀',risk:'medium',color:'#8b5cf6',cases:200000000,deaths:5000,mort:0.0025,countries:195,r0:0,trend:1,cat:'Virus',pathogen:'EBV (HHV-4)',vector:'Salive',transmission:'Salive (maladie du baiser)',host:'Humain',incub:'4–6 semaines',regions:['Mondial'],lat:35,lng:0,desc:'Mononucléose infectieuse. 90% adultes infectés. Lien lymphomes et SEP.',vaccine:{name:'En développement',maker:'Moderna',eff:0,status:'Essais',approved:'—',note:'Vaccin ARNm à l\'essai.',link:'https://www.who.int/'},econ:{direct:8,tour:1,agri:0,health:340,gdp:-0.1,jobs:70000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'cmv',name:'Cytomégalovirus (CMV)',emoji:'🫀',risk:'medium',color:'#8b5cf6',cases:100000000,deaths:8000,mort:0.008,countries:195,r0:0,trend:1,cat:'Virus',pathogen:'CMV (HHV-5)',vector:'Fluides',transmission:'Fluides corporels',host:'Humain',incub:'variable',regions:['Mondial'],lat:35,lng:0,desc:'Première cause infectieuse de malformations congénitales. Grave immunodéprimés.',vaccine:{name:'En développement',maker:'Moderna',eff:0,status:'Essais',approved:'—',note:'Ganciclovir. Vaccin à l\'essai.',link:'https://www.who.int/'},econ:{direct:6,tour:0,agri:0,health:420,gdp:-0.08,jobs:50000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'varicella',name:'Varicelle/Zona',emoji:'🔴',risk:'medium',color:'#ec4899',cases:140000000,deaths:20000,mort:0.014,countries:195,r0:10,trend:-2,cat:'Virus',pathogen:'VZV (HHV-3)',vector:'Respiratoire',transmission:'Gouttelettes, contact',host:'Humain',incub:'10–21 jours',regions:['Mondial'],lat:35,lng:0,desc:'Varicelle (enfants) puis zona (réactivation). Très contagieux.',vaccine:{name:'Varivax/Shingrix',maker:'Merck/GSK',eff:90,status:'Disponible',approved:'Mondial',note:'Vaccins varicelle et zona.',link:'https://www.who.int/'},econ:{direct:5,tour:1,agri:0,health:280,gdp:-0.06,jobs:45000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'gonorrhea',name:'Gonorrhée',emoji:'🎗️',risk:'high',color:'#dc2626',cases:82000000,deaths:5000,mort:0.006,countries:195,r0:0,trend:12,cat:'Bactérie',pathogen:'Neisseria gonorrhoeae',vector:'Sexuel',transmission:'Rapports sexuels',host:'Humain',incub:'2–14 jours',regions:['Mondial'],lat:20,lng:0,desc:'IST. Résistance antibiotique alarmante (super-gonorrhée). Infertilité.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Ceftriaxone (résistance croissante).',link:'https://www.who.int/'},econ:{direct:12,tour:2,agri:0,health:580,gdp:-0.2,jobs:120000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]}
,
{id:'syphilis',name:'Syphilis',emoji:'🎗️',risk:'high',color:'#dc2626',cases:8000000,deaths:200000,mort:2.5,countries:195,r0:0,trend:15,cat:'Bactérie',pathogen:'Treponema pallidum',vector:'Sexuel',transmission:'Sexuel, congénital',host:'Humain',incub:'3 semaines',regions:['Mondial'],lat:20,lng:0,desc:'IST. Résurgence mondiale. Syphilis congénitale en hausse. 4 stades.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Pénicilline.',link:'https://www.who.int/'},econ:{direct:8,tour:1,agri:0,health:420,gdp:-0.15,jobs:85000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'chlamydia',name:'Chlamydia',emoji:'🎗️',risk:'high',color:'#dc2626',cases:129000000,deaths:3000,mort:0.002,countries:195,r0:0,trend:8,cat:'Bactérie',pathogen:'Chlamydia trachomatis',vector:'Sexuel',transmission:'Rapports sexuels',host:'Humain',incub:'1–3 semaines',regions:['Mondial'],lat:25,lng:0,desc:'IST la plus fréquente. Souvent asymptomatique. Infertilité si non traitée.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Azithromycine/doxycycline.',link:'https://www.who.int/'},econ:{direct:10,tour:1,agri:0,health:520,gdp:-0.15,jobs:100000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'trichomoniasis',name:'Trichomonase',emoji:'🎗️',risk:'medium',color:'#f43f5e',cases:156000000,deaths:1000,mort:0.0006,countries:195,r0:0,trend:3,cat:'Parasite',pathogen:'Trichomonas vaginalis',vector:'Sexuel',transmission:'Rapports sexuels',host:'Humain',incub:'5–28 jours',regions:['Mondial'],lat:20,lng:0,desc:'IST parasitaire la plus fréquente. Souvent asymptomatique.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Métronidazole.',link:'https://www.who.int/'},econ:{direct:4,tour:0,agri:0,health:180,gdp:-0.05,jobs:35000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'herpes',name:'Herpès (HSV)',emoji:'🎗️',risk:'medium',color:'#f43f5e',cases:3700000000,deaths:5000,mort:0.0001,countries:195,r0:0,trend:2,cat:'Virus',pathogen:'HSV-1/HSV-2',vector:'Contact',transmission:'Contact, sexuel',host:'Humain',incub:'2–12 jours',regions:['Mondial'],lat:30,lng:0,desc:'67% population mondiale (HSV-1). Récurrent à vie. Herpès néonatal grave.',vaccine:{name:'En développement',maker:'Moderna/BioNTech',eff:0,status:'Essais',approved:'—',note:'Aciclovir.',link:'https://www.who.int/'},econ:{direct:8,tour:1,agri:0,health:380,gdp:-0.08,jobs:60000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'q_fever',name:'Fièvre Q',emoji:'🐑',risk:'medium',color:'#a16207',cases:60000,deaths:1200,mort:2,countries:100,r0:0,trend:2,cat:'Bactérie',pathogen:'Coxiella burnetii',vector:'Bétail',transmission:'Inhalation, animaux',host:'Bétail/ovins',incub:'2–3 semaines',regions:['Mondial'],lat:35,lng:20,desc:'Zoonose. Éleveurs et vétérinaires. Endocardite chronique possible.',vaccine:{name:'Q-Vax (Australie)',maker:'—',eff:83,status:'Disponible',approved:'Australie',note:'Doxycycline.',link:'https://www.who.int/'},econ:{direct:1,tour:0,agri:3,health:60,gdp:-0.02,jobs:12000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'tularemia',name:'Tularémie',emoji:'🐰',risk:'medium',color:'#78716c',cases:1000,deaths:20,mort:2,countries:50,r0:0,trend:1,cat:'Bactérie',pathogen:'Francisella tularensis',vector:'Tiques/animaux',transmission:'Tiques, animaux, aérosols',host:'Rongeurs/lièvres',incub:'3–5 jours',regions:['Hémisphère Nord'],lat:45,lng:20,desc:'Zoonose. Agent bioterrorisme potentiel. Fièvre du lièvre.',vaccine:{name:'En développement',maker:'—',eff:0,status:'Essais',approved:'—',note:'Streptomycine.',link:'https://www.cdc.gov/'},econ:{direct:1,tour:0,agri:1,health:30,gdp:-0.01,jobs:5000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'hendra',name:'Virus Hendra',emoji:'🐴',risk:'high',color:'#7c3aed',cases:7,deaths:4,mort:57,countries:2,r0:0.3,trend:0,cat:'Virus',pathogen:'Henipavirus Hendra',vector:'Chauves-souris/chevaux',transmission:'Chevaux infectés',host:'Chauves-souris frugivores',incub:'5–16 jours',regions:['Australie'],lat:-25,lng:145,desc:'Zoonose rare mais mortelle. Australie. Proche du Nipah.',vaccine:{name:'Equivac (chevaux)',maker:'—',eff:0,status:'Aucun',approved:'Vétérinaire',note:'Soins intensifs.',link:'https://www.who.int/'},econ:{direct:0.1,tour:0,agri:1,health:10,gdp:-0.01,jobs:1000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'lyme',name:'Maladie de Lyme',emoji:'🕷️',risk:'medium',color:'#65a30d',cases:600000,deaths:100,mort:0.017,countries:80,r0:0,trend:10,cat:'Bactérie',pathogen:'Borrelia burgdorferi',vector:'Tiques',transmission:'Morsure de tique',host:'Rongeurs/cerfs',incub:'3–30 jours',regions:['Amérique du Nord','Europe'],lat:45,lng:-75,desc:'Borréliose. Érythème migrant. Complications articulaires/neurologiques. En hausse.',vaccine:{name:'VLA15 (essais)',maker:'Pfizer/Valneva',eff:0,status:'Essais',approved:'—',note:'Doxycycline.',link:'https://www.cdc.gov/'},econ:{direct:8,tour:3,agri:0,health:340,gdp:-0.08,jobs:65000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'ehrlichiosis',name:'Ehrlichiose',emoji:'🕷️',risk:'medium',color:'#65a30d',cases:5000,deaths:50,mort:1,countries:40,r0:0,trend:8,cat:'Bactérie',pathogen:'Ehrlichia',vector:'Tiques',transmission:'Morsure de tique',host:'Cerfs/chiens',incub:'1–2 semaines',regions:['Amérique du Nord'],lat:38,lng:-90,desc:'Zoonose transmise par tiques. En augmentation avec le réchauffement.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Doxycycline.',link:'https://www.cdc.gov/'},econ:{direct:1,tour:1,agri:0,health:40,gdp:-0.01,jobs:8000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'babesiosis',name:'Babésiose',emoji:'🕷️',risk:'medium',color:'#65a30d',cases:2000,deaths:40,mort:2,countries:30,r0:0,trend:9,cat:'Parasite',pathogen:'Babesia microti',vector:'Tiques',transmission:'Morsure de tique, transfusion',host:'Rongeurs',incub:'1–4 semaines',regions:['Amérique du Nord'],lat:42,lng:-72,desc:'Paludisme-like transmis par tiques. Grave chez immunodéprimés/spléno.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Atovaquone + azithromycine.',link:'https://www.cdc.gov/'},econ:{direct:1,tour:0,agri:0,health:35,gdp:-0.01,jobs:5000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]}
,
{id:'rocky_mountain',name:'Fièvre pourprée (RMSF)',emoji:'🕷️',risk:'high',color:'#b91c1c',cases:6000,deaths:300,mort:5,countries:30,r0:0,trend:5,cat:'Bactérie',pathogen:'Rickettsia rickettsii',vector:'Tiques',transmission:'Morsure de tique',host:'Chiens/rongeurs',incub:'2–14 jours',regions:['Amériques'],lat:35,lng:-95,desc:'Rickettsiose grave. Mortelle sans traitement rapide. Éruption caractéristique.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Doxycycline urgente.',link:'https://www.cdc.gov/'},econ:{direct:1,tour:1,agri:0,health:50,gdp:-0.01,jobs:8000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]},
{id:'marburg_hemorrhagic',name:'Fièvre de Marseille (boutonneuse)',emoji:'🕷️',risk:'medium',color:'#dc2626',cases:10000,deaths:250,mort:2.5,countries:40,r0:0,trend:3,cat:'Bactérie',pathogen:'Rickettsia conorii',vector:'Tiques',transmission:'Morsure de tique du chien',host:'Chiens',incub:'6 jours',regions:['Méditerranée','Afrique'],lat:38,lng:15,desc:'Rickettsiose méditerranéenne. Tache noire au site de morsure.',vaccine:{name:'Aucun',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Doxycycline.',link:'https://www.who.int/'},econ:{direct:1,tour:1,agri:0,health:40,gdp:-0.01,jobs:6000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'monkeypox_clade2',name:'Mpox Clade II',emoji:'🔴',risk:'medium',color:'#f97316',cases:95000,deaths:180,mort:0.19,countries:120,r0:1.8,trend:5,cat:'Virus',pathogen:'MPXV clade II',vector:'Contact',transmission:'Contact étroit, sexuel',host:'Rongeurs',incub:'5–21 jours',regions:['Mondial'],lat:10,lng:20,desc:'Souche de l\'épidémie mondiale 2022. Moins sévère que clade I.',vaccine:{name:'Jynneos',maker:'Bavarian Nordic',eff:85,status:'Disponible',approved:'Mondial',note:'Vaccin antivariolique.',link:'https://www.who.int/'},econ:{direct:5,tour:3,agri:0,health:220,gdp:-0.1,jobs:60000},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'sars',name:'SRAS (SARS-CoV-1)',emoji:'🫁',risk:'watch',color:'#7c3aed',cases:8, deaths:0,mort:9.6,countries:1,r0:3,trend:0,cat:'Virus',pathogen:'SARS-CoV-1',vector:'Respiratoire',transmission:'Gouttelettes',host:'Chauves-souris/civettes',incub:'2–7 jours',regions:['Asie'],lat:23,lng:113,desc:'Coronavirus de 2003. Éradiqué depuis 2004 mais surveillance maintenue.',vaccine:{name:'Recherche',maker:'—',eff:0,status:'Aucun',approved:'—',note:'Surveillance.',link:'https://www.who.int/'},econ:{direct:0,tour:0,agri:0,health:5,gdp:0,jobs:0},src:[{n:'OMS',u:'https://www.who.int/',t:'WHO'}]},
{id:'swine_flu_h1n2',name:'Grippe porcine H1N2v',emoji:'🐷',risk:'watch',color:'#f472b6',cases:120,deaths:3,mort:2.5,countries:5,r0:1.2,trend:15,cat:'Virus',pathogen:'Influenza A(H1N2)v',vector:'Porcs',transmission:'Contact porcs, humain-humain limité',host:'Porcs',incub:'1–4 jours',regions:['Amérique du Nord','Europe'],lat:40,lng:-90,desc:'Grippe variante porcine. Surveillance pandémique. Foires agricoles à risque.',vaccine:{name:'Prototype',maker:'CDC',eff:0,status:'Essais',approved:'—',note:'Oseltamivir. Potentiel pandémique surveillé.',link:'https://www.cdc.gov/'},econ:{direct:1,tour:0,agri:3,health:40,gdp:-0.02,jobs:8000},src:[{n:'CDC',u:'https://www.cdc.gov/',t:'CDC'}]}
],

alerts:[
{type:'critical',color:'#ef4444',text:'🔴 MARBURG — Tanzanie: 14 cas, 11 décès. District Kagera. Barrière sanitaire active.',time:'Il y a 2h',did:'marburg'},
{type:'critical',color:'#ef4444',text:'🔴 DENGUE — Brésil: +34% admissions S23/2026. São Paulo état urgence sanitaire.',time:'Il y a 3h',did:'dengue'},
{type:'critical',color:'#f97316',text:'🔴 H5N1 — USA: mutation PB2 627K souches bovines Minnesota. Alerte pandémique.',time:'Il y a 5h',did:'h5n1'},
{type:'high',color:'#f97316',text:'🟠 MPOX Clade Ib — Thaïlande: 3 premiers cas autochtones. Expansion asiatique.',time:'Il y a 7h',did:'mpox'},
{type:'high',color:'#f97316',text:'🟠 CHOLÉRA — Soudan: 48 000 cas/6 semaines. Systèmes sanitaires effondrés.',time:'Il y a 8h',did:'cholera'},
{type:'high',color:'#f97316',text:'🟠 COQUELUCHE — Philippines: +370% cas 2026. Couverture DTP <60%.',time:'Il y a 12h',did:'pertussis'},
{type:'medium',color:'#eab308',text:'🟡 ROUGEOLE — Roumanie: 4 comtés, 1 200 cas. Couverture ROR 78%.',time:'Il y a 1j',did:'measles'},
{type:'medium',color:'#eab308',text:'🟡 CANDIDA AURIS — Mumbai: 28 patients, 12 décès. Résistant 3 classes.',time:'Il y a 1j',did:'candida'},
{type:'watch',color:'#3b82f6',text:'🔵 NIPAH — Kerala: mortalité canine Kozhikode. Surveillance renforcée.',time:'Il y a 2j',did:'nipah'},
{type:'watch',color:'#3b82f6',text:'🔵 HANTAVIRUS — USA: 3 cas Nouveau-Mexique, rongeurs Peromyscus.',time:'Il y a 3j',did:'hantavirus'},
],

science:[
{t:'H5N1: Mammalian Adaptation (1,240 genomes)',j:'Nature Medicine',src:'Nature',d:'15 juin 2026',stars:5,sum:'PB2 627K souches bovines USA — marqueur adaptatif critique.',method:'NGS Illumina + phylogénétique MaxClade',url:'https://www.who.int/publications/m/item/avian-influenza-a(h5n1)-situation-updates'},
{t:'Dengue Qdenga TAK-003: 4-Year Real-World Efficacy',j:'Lancet Infectious Diseases',src:'Lancet',d:'10 juin 2026',stars:5,sum:'80.2% efficacité dengue sévère tous sérotypes sur 4 ans.',method:'Essai randomisé multicentrique',url:'https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(23)00028-7'},
{t:'Mpox Clade Ib: Genomic Characterization',j:'NEJM',src:'NEJM',d:'5 juin 2026',stars:5,sum:'7 mutations distinctives, transmissibilité sexuelle supérieure.',method:'Oxford Nanopore + contact tracing',url:'https://www.nejm.org/doi/full/10.1056/NEJMoa2401220'},
{t:'Antimicrobial Resistance: Global Burden 2025',j:'The Lancet',src:'Lancet',d:'2 juin 2026',stars:5,sum:'1.27M décès/an. Projection 10M/an 2050.',method:'Méta-analyse 204 pays GRAM',url:'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)02724-0'},
{t:'R21/Matrix-M Malaria Vaccine: 5 Countries',j:'The Lancet',src:'Lancet',d:'28 mai 2026',stars:5,sum:'77% efficacité clinique, 94% formes graves sur 18 mois.',method:'Phase 3 RCT double-aveugle',url:'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)01311-3'},
{t:'Lenakapavir HIV Prevention: PURPOSE 1',j:'The Lancet',src:'Lancet',d:'1 mai 2026',stars:5,sum:'100% efficacité VIH femmes Afrique (n=5 338).',method:'Phase 3 RCT 25 sites Afrique',url:'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(24)01183-3'},
{t:'Candida auris: 58 Countries Expansion',j:'CDC MMWR',src:'CDC',d:'20 mai 2026',stars:4,sum:'58 pays. Ibrexafungerp actif résistants.',method:'Surveillance CDC + ECDC',url:'https://www.cdc.gov/candida-auris/'},
{t:'ECDC Influenza 2025-2026 Season',j:'Eurosurveillance',src:'WHO',d:'10 avr 2026',stars:4,sum:'H3N2 dominant. 47% efficacité vaccin.',method:'EISN 41 pays + FluNet',url:'https://www.ecdc.europa.eu/en/seasonal-influenza'},
{t:'WHO Fungal Priority Pathogens 2025',j:'WHO Report',src:'WHO',d:'15 mars 2026',stars:4,sum:'3.8M décès/an champignons. C.auris priorité 1.',method:'Évaluation multicritère OMS',url:'https://www.who.int/publications/i/item/9789240060241'},
{t:'One Health: AI Zoonotic Early Warning',j:'Nature Medicine',src:'Nature',d:'1 mars 2026',stars:4,sum:'IA 2.3M signaux/jour: 14j avance sur 80% émergences.',method:'Random Forest + LSTM',url:'https://www.who.int/initiatives/goarn'},
],
};

const RC={critical:'bc',high:'bh',medium:'bm',low:'bl',watch:'bw'};

// Assistant IA config — zéro carte bancaire requise
const GROQ_URL='https://api.groq.com/openai/v1/chat/completions';
// IA avancée : modèle IA le plus récent (coupure plus tardive que 3.3)
let GROQ_MODEL='openai/gpt-oss-120b';
// Modèle de secours si Scout indisponible
const GROQ_MODEL_FALLBACK='openai/gpt-oss-20b';

// ════════════════════════════════════════════════════════════════
// 🔑 ADMINISTRATEUR : METS TES CLÉS ICI (entre les guillemets)
// ════════════════════════════════════════════════════════════════
// Clé Assistant IA — obtiens-la sur console.groq.com (commence par gsk_)
const ADMIN_AI_KEY = '';
// Clé Recherche Web — obtiens-la sur tavily.com (commence par tvly-)
const ADMIN_WEB_KEY = '';
// ════════════════════════════════════════════════════════════════

let GROQ_KEY = ADMIN_AI_KEY || localStorage.getItem('wdm_groq_key') || '';

// Recherche Web — recherche web temps réel (1000 crédits gratuits/mois, zéro carte)
const TAVILY_URL='https://api.tavily.com/search';
let TAVILY_KEY = ADMIN_WEB_KEY || localStorage.getItem('wdm_tavily_key') || '';

// ─── ESTIMATION CAS PAR PAYS POUR CHAQUE MALADIE ─────────────────
// Utilisé pour dimensionner les cercles sur la carte
// Basé sur les données OMS/CDC de répartition géographique
const DISEASE_CASE_WEIGHTS = {
  // Pour chaque maladie, poids relatif par pays (les gros foyers ont plus de poids)
  dengue: {BR:2800000,IN:580000,ID:340000,PH:290000,VN:180000,TH:150000,MY:120000,CO:95000,MX:78000,PE:52000,BD:48000,LK:42000,NG:38000,BF:12000,SN:8500,ML:6200,CI:9800,GH:11000,KH:28000,LA:15000,MM:34000,CU:8900,DO:12000,HN:18000,GT:14000,NI:9200,VE:22000,EC:16000,BO:11000,PY:8400,SG:6800,TW:9100,AU:4200,FJ:2100,KE:5600,TZ:7200,CM:8900,CD:15000,GN:4800,SL:3900,LR:2800,GM:1900,TG:5100,BJ:6200,NE:3400,CF:2800},
  covid19: {}, // rempli par l'API en temps réel
  malaria: {NG:1200000,CD:680000,ET:340000,MZ:290000,TZ:280000,UG:270000,KE:180000,ML:145000,CM:138000,GH:125000,BF:118000,SN:52000,CI:98000,GN:78000,MR:34000,TG:56000,BJ:62000,NE:48000,CF:38000,CG:42000,AO:145000,ZM:98000,ZW:56000,MW:78000,MG:112000,SS:98000,SD:78000,BI:56000,RW:34000,IN:340000,MM:78000,TH:12000,ID:56000,PG:98000,PH:8900,MY:5600,BD:34000,PK:56000,AF:78000,SL:45000,LR:38000,GW:12000,US:2000,GB:1800,FR:2600,DE:1000,IT:600,ES:700,CA:500,AU:400,BE:300,NL:350,SE:200,CH:250,PT:400,JP:150,KR:80,CN:3000,SA:2500,AE:1500,QA:800,ZA:10000,BR:140000,CO:80000,VE:230000,PE:25000,EC:2000,BO:8000,GY:15000,SR:1200,HN:5000,GT:5000,NI:3000,PA:800,CR:100,MX:800,DO:1000,HT:20000},
  cholera: {HT:98000,YE:145000,SO:78000,SY:56000,AF:45000,SD:120000,SS:78000,ET:56000,NG:145000,CD:98000,ZM:34000,MW:28000,TZ:45000,MZ:38000,GH:12000,CM:18000,IQ:8900,SL:12000,GN:9800,GW:5600,LR:6800,SN:8900,ML:7200,NE:5400,CF:4800,CG:6200,AO:12000,KE:18000,UG:24000},
  measles: {NG:98000,ET:56000,CD:78000,SD:34000,SS:28000,SO:24000,CF:12000,ML:18000,NE:22000,BF:16000,CM:19000,GN:8900,GW:4200,SL:6800,LR:5400,TG:9200,BJ:11000,YE:34000,AF:45000,PK:56000,IN:78000,PH:34000,ID:28000,BD:24000,MM:18000,UA:12000,RO:8900},
  mpox: {CD:52000,NG:8900,CM:4200,CF:2800,CG:3400,GH:2100,CI:1900,TZ:1600,KE:1200,SN:890,ML:680,GN:560,RW:1100,UG:1400,BI:780,ZM:920,US:3400,CA:890,GB:1200,FR:1600,DE:1400,ES:1800,IT:1200,BE:680,NL:590,SE:340,PT:450,BR:2100,TH:340,IN:560,MY:280,SG:190},
  h5n1: {US:34,CA:8,MX:4,IN:6,VN:12,TH:8,ID:14,PH:4,MY:3,BD:9,EG:12,SD:5,NG:8,GH:4,CM:3,CN:18,JP:6,KR:5,MN:3,KZ:4,RU:8,FR:6,DE:5,GB:4,NL:3,BE:2,PL:4,CZ:3,RO:5,UA:6},
  tb: {IN:340000,CN:98000,ID:145000,PH:120000,PK:98000,NG:78000,BD:145000,ZA:98000,CD:56000,TZ:45000,ET:56000,MZ:34000,MM:45000,VN:34000,TH:28000,ID:145000,RU:56000,UA:34000,KZ:18000,PE:24000,BR:45000},
  hiv: {ZA:340000,MZ:145000,NG:120000,KE:98000,TZ:98000,UG:78000,ZM:78000,ZW:98000,MW:56000,ET:56000,CD:45000,CM:34000,CI:38000,GH:28000,SN:8900,IN:145000,TH:34000,VN:28000,ID:56000,RU:98000,UA:56000,BR:56000,US:38000},
  yellow_fever: {NG:2800,CD:1200,CI:890,GH:680,CM:560,SN:340,ML:280,GN:420,SL:190,LR:160,BF:240,TG:180,BJ:220,NE:140,CF:120,CG:180,AO:340,ZM:120,ET:180,SD:140,UG:220,KE:180,TZ:240,BR:1600,CO:890,PE:560,EC:340,BO:280,VE:180,GY:120,SR:90},
  ebola: {CD:28,CG:6,SS:4,GA:3,GQ:2,GN:8,SL:4,LR:3,NG:2},
  marburg: {TZ:12,CD:2},
  meningitis: {NG:340000,ML:120000,BF:98000,NE:78000,GH:56000,CM:45000,TD:38000,CF:24000,SD:34000,SS:28000,ET:45000,KE:34000,TZ:28000,SN:18000,GN:12000,SL:9800,LR:8900,GM:5600},
  pertussis: {PH:45000,CN:56000,IN:78000,AU:12000,US:34000,GB:8900,FR:12000,DE:9800,BR:24000,ID:18000,VN:14000,BD:16000,PK:22000,NG:34000,ET:18000},
  lassa: {NG:8900,SL:1200,GN:890,LR:680,CI:560,ML:340,GH:280,SN:190,BF:240,BJ:180,TG:160},
  hep_b: {CN:2800000,IN:1200000,ID:680000,NG:560000,PH:340000,VN:290000,ET:180000,PK:340000,BD:280000,EG:145000},
  chikungunya: {IN:145000,BR:98000,TH:34000,ID:28000,PH:24000,MY:18000,CO:34000,VE:18000,PE:12000},
  zika: {BR:12000,CO:4800,VE:2800,PE:1900,MX:3400,TH:890,ID:560,PH:680,IN:1200},
  rabies: {IN:20000,CN:5600,PH:340,PK:4200,BD:2100,ID:890,ET:2800,NG:1900,MM:680},
  amr: {IN:340000,CN:280000,PK:145000,US:180000,BD:98000,ID:78000,NG:120000,BR:98000,RU:78000},
  influenza: {US:145000,CN:280000,IN:340000,BR:98000,RU:78000,JP:56000,DE:45000,FR:56000,GB:34000},
  polio: {PK:120,AF:98,NG:56,SS:24,CD:18,ET:12,YE:34,SD:28},
  nipah: {IN:6,BD:2,MY:1},
  hantavirus: {US:340,AR:280,CL:190,BR:240,CA:120,DE:180,RU:220,CN:340,KR:180},
  candida: {US:2800,IN:1900,ZA:890,GB:680,DE:560,ES:780,FR:450,BR:340,CO:280},
  mers: {SA:1400,AE:180,QA:120,KW:98,OM:78,JO:56,KR:186,GB:12},
};
